# Ejercicios diarios mySQL

## Importacion de los datos y librerias

In [43]:
## Conectarse a docker y pandas
import pandas as pd
import os
from sqlalchemy import create_engine

In [44]:
from dotenv import load_dotenv
import cryptography
load_dotenv("credenciales/sakila.env")

True

## Creacion usuario para conectarse a base de datos

In [45]:
user = os.getenv("MYSQL_USER")
pwd  = os.environ["MYSQL_PASSWORD"]
host = os.getenv("MYSQL_HOST")
port = os.getenv("MYSQL_PORT")
db   = os.getenv("MYSQL_DB")

engine = create_engine(f"mysql+pymysql://{user}:{pwd}@{host}:{port}/{db}")

In [46]:
print("cwd:", os.getcwd())
print("MYSQL_USER:", os.getenv("MYSQL_USER"))
print("MYSQL_PASSWORD existe?:", os.getenv("MYSQL_PASSWORD") is not None)
print("MYSQL_DB existe?:", os.getenv("MYSQL_DB"))

cwd: c:\Users\workw\Documents\practicar programacion\sql
MYSQL_USER: usuario_sakila
MYSQL_PASSWORD existe?: True
MYSQL_DB existe?: sakila

## Practica clausulas y operadores

In [47]:
pd.read_sql("SHOW TABLES;", engine)

              Tables_in_sakila
0                        actor
1                   actor_info
2                      address
3                     category
4                         city
5                      country
6                     customer
7                customer_list
8                         film
9                   film_actor
10               film_category
11                   film_list
12                   film_text
13                   inventory
14                    language
15  nicer_but_slower_film_list
16                     payment
17                      rental
18      sales_by_film_category
19              sales_by_store
20                       staff
21                  staff_list
22                       store

In [48]:
pd.read_sql("SELECT category, COUNT(*) AS n FROM film_list GROUP BY category ORDER BY n DESC;", engine)

       category   n
0        Sports  74
1       Foreign  73
2        Family  69
3   Documentary  68
4     Animation  66
5        Action  64
6           New  63
7         Drama  62
8        Sci-Fi  61
9         Games  61
10     Children  60
11       Comedy  58
12     Classics  57
13       Travel  57
14       Horror  56
15        Music  51

In [49]:
pd.read_sql("DESCRIBE film_list;", engine)

         Field                                Type Null Key Default Extra
0          FID                   smallint unsigned   NO           0
1        title                        varchar(128)   NO         NaN
2  description                                text  YES         NaN
3     category                         varchar(25)  YES         NaN
4        price                        decimal(4,2)   NO        4.99
5       length                   smallint unsigned  YES         NaN
6       rating  enum('G','PG','PG-13','R','NC-17')  YES           G
7       actors                                text  YES         NaN

In [50]:
pd.read_sql("SELECT title FROM film_list;", engine)

                 title
0     ACADEMY DINOSAUR
1       ACE GOLDFINGER
2     ADAPTATION HOLES
3     AFFAIR PREJUDICE
4          AFRICAN EGG
..                 ...
995     YOUNG LANGUAGE
996         YOUTH KICK
997       ZHIVAGO CORE
998  ZOOLANDER FICTION
999          ZORRO ARK

[1000 rows x 1 columns]

In [51]:
pd.read_sql("SELECT title FROM film_list WHERE category = 'Documentary';", engine)

                  title
0      ACADEMY DINOSAUR
1      ADAPTATION HOLES
2      ARMY FLINTSTONES
3   BEACH HEARTBREAKERS
4          BED HIGHBALL
..                  ...
63           WARS PLUTO
64       WEDDING APOLLO
65            WIFE TURN
66           WRATH MILE
67       YOUNG LANGUAGE

[68 rows x 1 columns]

In [52]:
pd.read_sql("SELECT * FROM film_list WHERE price BETWEEN 1 AND 3;", engine)

,FID,title,description,category,price,length,rating,actors
0,3,ADAPTATION HOLES,A Astounding Reflection of a Lumberjack And a ...,Documentary,2.99,50,NC-17,"NICK WAHLBERG, BOB FAWCETT, CAMERON STREEP, RA..."
1,4,AFFAIR PREJUDICE,A Fanciful Documentary of a Frisbee And a Lumb...,Horror,2.99,117,G,"JODIE DEGENERES, SCARLETT DAMON, KENNETH PESCI..."
2,5,AFRICAN EGG,A Fast-Paced Documentary of a Pastry Chef And ...,Family,2.99,130,G,"DUSTIN TAUTOU, THORA TEMPLE, MATTHEW CARREY, M..."
3,6,AGENT TRUMAN,A Intrepid Panorama of a Robot And a Boy who m...,Foreign,2.99,169,PG,"KIRSTEN PALTROW, SANDRA KILMER, JAYNE NEESON, ..."
4,9,ALABAMA DEVIL,A Thoughtful Panorama of a Database Administra...,Horror,2.99,114,PG-13,"WARREN NOLTE, GRETA KEITEL, WILLIAM HACKMAN, M..."
...,...,...,...,...,...,...,...,...
318,987,WORDS HUNTER,A Action-Packed Reflection of a Composer And a...,Music,2.99,116,PG,"GENE WILLIS, SUSAN DAVIS, SCARLETT BENING, ADA..."
319,988,WORKER TARZAN,A Action-Packed Yarn of a Secret Agent And a T...,Travel,2.99,139,R,"JULIANNE DENCH, ROCK DUKAKIS, MERYL GIBSON, MI..."
320,991,WORST BANGER,A Thrilling Drama of a Madman And a Dentist wh...,Action,2.99,185,PG,"PARKER GOLDBERG, KIRSTEN AKROYD, SPENCER DEPP,..."
321,993,WRONG BEHAVIOR,A Emotional Saga of a Crocodile And a Sumo Wre...,Children,2.99,178,PG-13,"THORA TEMPLE, GARY PHOENIX, GREGORY GOODING, M..."
322,999,ZOOLANDER FICTION,A Fateful Reflection of a Waitress And a Boat ...,Children,2.99,101,R,"CARMEN HUNT, MARY TANDY, PENELOPE CRONYN, WHOO..."

In [53]:
pd.read_sql("SELECT * FROM film_list WHERE price > 1 AND price < 3;", engine)

,FID,title,description,category,price,length,rating,actors
0,3,ADAPTATION HOLES,A Astounding Reflection of a Lumberjack And a ...,Documentary,2.99,50,NC-17,"NICK WAHLBERG, BOB FAWCETT, CAMERON STREEP, RA..."
1,4,AFFAIR PREJUDICE,A Fanciful Documentary of a Frisbee And a Lumb...,Horror,2.99,117,G,"JODIE DEGENERES, SCARLETT DAMON, KENNETH PESCI..."
2,5,AFRICAN EGG,A Fast-Paced Documentary of a Pastry Chef And ...,Family,2.99,130,G,"DUSTIN TAUTOU, THORA TEMPLE, MATTHEW CARREY, M..."
3,6,AGENT TRUMAN,A Intrepid Panorama of a Robot And a Boy who m...,Foreign,2.99,169,PG,"KIRSTEN PALTROW, SANDRA KILMER, JAYNE NEESON, ..."
4,9,ALABAMA DEVIL,A Thoughtful Panorama of a Database Administra...,Horror,2.99,114,PG-13,"WARREN NOLTE, GRETA KEITEL, WILLIAM HACKMAN, M..."
...,...,...,...,...,...,...,...,...
318,987,WORDS HUNTER,A Action-Packed Reflection of a Composer And a...,Music,2.99,116,PG,"GENE WILLIS, SUSAN DAVIS, SCARLETT BENING, ADA..."
319,988,WORKER TARZAN,A Action-Packed Yarn of a Secret Agent And a T...,Travel,2.99,139,R,"JULIANNE DENCH, ROCK DUKAKIS, MERYL GIBSON, MI..."
320,991,WORST BANGER,A Thrilling Drama of a Madman And a Dentist wh...,Action,2.99,185,PG,"PARKER GOLDBERG, KIRSTEN AKROYD, SPENCER DEPP,..."
321,993,WRONG BEHAVIOR,A Emotional Saga of a Crocodile And a Sumo Wre...,Children,2.99,178,PG-13,"THORA TEMPLE, GARY PHOENIX, GREGORY GOODING, M..."
322,999,ZOOLANDER FICTION,A Fateful Reflection of a Waitress And a Boat ...,Children,2.99,101,R,"CARMEN HUNT, MARY TANDY, PENELOPE CRONYN, WHOO..."

In [54]:
pd.read_sql("DESCRIBE actor_info;", engine)

        Field               Type Null Key Default Extra
0    actor_id  smallint unsigned   NO           0
1  first_name        varchar(45)   NO         NaN
2   last_name        varchar(45)   NO         NaN
3   film_info               text  YES         NaN

In [55]:
pd.read_sql("DESCRIBE country;", engine)

,Field,Type,Null,Key,Default,Extra
0,country_id,smallint unsigned,NO,PRI,NaN,auto_increment
1,country,varchar(50),NO,,NaN,
2,last_update,timestamp,NO,,CURRENT_TIMESTAMP,DEFAULT_GENERATED on update CURRENT_TIMESTAMP

In [56]:
# No olvidar poner comillas al dato de la variable categorica (no olvidar poner comillas a Algeria)
pd.read_sql("SELECT * FROM country WHERE country != 'Algeria';", engine)

     country_id               country         last_update
0             1           Afghanistan 2006-02-15 04:44:00
1             3        American Samoa 2006-02-15 04:44:00
2             4                Angola 2006-02-15 04:44:00
3             5              Anguilla 2006-02-15 04:44:00
4             6             Argentina 2006-02-15 04:44:00
..          ...                   ...                 ...
103         105               Vietnam 2006-02-15 04:44:00
104         106  Virgin Islands, U.S. 2006-02-15 04:44:00
105         107                 Yemen 2006-02-15 04:44:00
106         108            Yugoslavia 2006-02-15 04:44:00
107         109                Zambia 2006-02-15 04:44:00

[108 rows x 3 columns]

In [57]:
pd.read_sql("SELECT * FROM country WHERE country <> 'Algeria';", engine)

     country_id               country         last_update
0             1           Afghanistan 2006-02-15 04:44:00
1             3        American Samoa 2006-02-15 04:44:00
2             4                Angola 2006-02-15 04:44:00
3             5              Anguilla 2006-02-15 04:44:00
4             6             Argentina 2006-02-15 04:44:00
..          ...                   ...                 ...
103         105               Vietnam 2006-02-15 04:44:00
104         106  Virgin Islands, U.S. 2006-02-15 04:44:00
105         107                 Yemen 2006-02-15 04:44:00
106         108            Yugoslavia 2006-02-15 04:44:00
107         109                Zambia 2006-02-15 04:44:00

[108 rows x 3 columns]

In [58]:
pd.read_sql("SELECT * FROM country WHERE country NOT IN ('Algeria', 'ARGENTINA');", engine)

     country_id               country         last_update
0             1           Afghanistan 2006-02-15 04:44:00
1             3        American Samoa 2006-02-15 04:44:00
2             4                Angola 2006-02-15 04:44:00
3             5              Anguilla 2006-02-15 04:44:00
4             7               Armenia 2006-02-15 04:44:00
..          ...                   ...                 ...
102         105               Vietnam 2006-02-15 04:44:00
103         106  Virgin Islands, U.S. 2006-02-15 04:44:00
104         107                 Yemen 2006-02-15 04:44:00
105         108            Yugoslavia 2006-02-15 04:44:00
106         109                Zambia 2006-02-15 04:44:00

[107 rows x 3 columns]

## Practica consultas de agregacion

In [59]:
pd.read_sql("SELECT * FROM film",engine)

,film_id,title,description,release_year,language_id,original_language_id,rental_duration,rental_rate,length,replacement_cost,rating,special_features,last_update
0,1,ACADEMY DINOSAUR,A Epic Drama of a Feminist And a Mad Scientist...,2006,1,None,6,0.99,86,20.99,PG,"Deleted Scenes,Behind the Scenes",2006-02-15 05:03:42
1,2,ACE GOLDFINGER,A Astounding Epistle of a Database Administrat...,2006,1,None,3,4.99,48,12.99,G,"Trailers,Deleted Scenes",2006-02-15 05:03:42
2,3,ADAPTATION HOLES,A Astounding Reflection of a Lumberjack And a ...,2006,1,None,7,2.99,50,18.99,NC-17,"Trailers,Deleted Scenes",2006-02-15 05:03:42
3,4,AFFAIR PREJUDICE,A Fanciful Documentary of a Frisbee And a Lumb...,2006,1,None,5,2.99,117,26.99,G,"Commentaries,Behind the Scenes",2006-02-15 05:03:42
4,5,AFRICAN EGG,A Fast-Paced Documentary of a Pastry Chef And ...,2006,1,None,6,2.99,130,22.99,G,Deleted Scenes,2006-02-15 05:03:42
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,YOUNG LANGUAGE,A Unbelieveable Yarn of a Boat And a Database ...,2006,1,None,6,0.99,183,9.99,G,"Trailers,Behind the Scenes",2006-02-15 05:03:42
996,997,YOUTH KICK,A Touching Drama of a Teacher And a Cat who mu...,2006,1,None,4,0.99,179,14.99,NC-17,"Trailers,Behind the Scenes",2006-02-15 05:03:42
997,998,ZHIVAGO CORE,A Fateful Yarn of a Composer And a Man who mus...,2006,1,None,6,0.99,105,10.99,NC-17,Deleted Scenes,2006-02-15 05:03:42
998,999,ZOOLANDER FICTION,A Fateful Reflection of a Waitress And a Boat ...,2006,1,None,5,2.99,101,28.99,R,"Trailers,Deleted Scenes",2006-02-15 05:03:42
999,1000,ZORRO ARK,A Intrepid Panorama of a Mad Scientist And a B...,2006,1,None,3,4.99,50,18.99,NC-17,"Trailers,Commentaries,Behind the Scenes",2006-02-15 05:03:42

In [60]:
pd.read_sql("SELECT rating, COUNT(film_id) AS frecuencia FROM film GROUP BY rating ORDER BY frecuencia DESC",engine)

  rating  frecuencia
0  PG-13         223
1  NC-17         210
2      R         195
3     PG         194
4      G         178

In [61]:
pd.read_sql("SELECT AVG(length) FROM film",engine)

   AVG(length)
0      115.272

In [62]:
pd.read_sql("SELECT rating, AVG(length) AS promedio_duracion FROM film GROUP BY rating ORDER BY promedio_duracion DESC",engine)

  rating  promedio_duracion
0  PG-13           120.4439
1      R           118.6615
2  NC-17           113.2286
3     PG           112.0052
4      G           111.0506

In [63]:
pd.read_sql("SELECT * FROM customer",engine)

,customer_id,store_id,first_name,last_name,email,address_id,active,create_date,last_update
0,1,1,MARY,SMITH,MARY.SMITH@sakilacustomer.org,5,1,2006-02-14 22:04:36,2006-02-15 04:57:20
1,2,1,PATRICIA,JOHNSON,PATRICIA.JOHNSON@sakilacustomer.org,6,1,2006-02-14 22:04:36,2006-02-15 04:57:20
2,3,1,LINDA,WILLIAMS,LINDA.WILLIAMS@sakilacustomer.org,7,1,2006-02-14 22:04:36,2006-02-15 04:57:20
3,4,2,BARBARA,JONES,BARBARA.JONES@sakilacustomer.org,8,1,2006-02-14 22:04:36,2006-02-15 04:57:20
4,5,1,ELIZABETH,BROWN,ELIZABETH.BROWN@sakilacustomer.org,9,1,2006-02-14 22:04:36,2006-02-15 04:57:20
...,...,...,...,...,...,...,...,...,...
594,595,1,TERRENCE,GUNDERSON,TERRENCE.GUNDERSON@sakilacustomer.org,601,1,2006-02-14 22:04:37,2006-02-15 04:57:20
595,596,1,ENRIQUE,FORSYTHE,ENRIQUE.FORSYTHE@sakilacustomer.org,602,1,2006-02-14 22:04:37,2006-02-15 04:57:20
596,597,1,FREDDIE,DUGGAN,FREDDIE.DUGGAN@sakilacustomer.org,603,1,2006-02-14 22:04:37,2006-02-15 04:57:20
597,598,1,WADE,DELVALLE,WADE.DELVALLE@sakilacustomer.org,604,1,2006-02-14 22:04:37,2006-02-15 04:57:20
598,599,2,AUSTIN,CINTRON,AUSTIN.CINTRON@sakilacustomer.org,605,1,2006-02-14 22:04:37,2006-02-15 04:57:20

In [64]:
pd.read_sql("SELECT store_id, COUNT(customer_id) FROM customer GROUP BY store_id", engine)

   store_id  COUNT(customer_id)
0         1                 326
1         2                 273

In [65]:
pd.read_sql("SELECT * FROM payment",engine)

,payment_id,customer_id,staff_id,rental_id,amount,payment_date,last_update
0,1,1,1,76,2.99,2005-05-25 11:30:37,2006-02-15 22:12:30
1,2,1,1,573,0.99,2005-05-28 10:35:23,2006-02-15 22:12:30
2,3,1,1,1185,5.99,2005-06-15 00:54:12,2006-02-15 22:12:30
3,4,1,2,1422,0.99,2005-06-15 18:02:53,2006-02-15 22:12:30
4,5,1,2,1476,9.99,2005-06-15 21:08:46,2006-02-15 22:12:30
...,...,...,...,...,...,...,...
16039,16045,599,1,14599,4.99,2005-08-21 17:43:42,2006-02-15 22:24:12
16040,16046,599,1,14719,1.99,2005-08-21 21:41:57,2006-02-15 22:24:12
16041,16047,599,2,15590,8.99,2005-08-23 06:09:44,2006-02-15 22:24:12
16042,16048,599,2,15719,2.99,2005-08-23 11:08:46,2006-02-15 22:24:13
16043,16049,599,2,15725,2.99,2005-08-23 11:25:00,2006-02-15 22:24:13

In [66]:
pd.read_sql("SELECT customer_id, AVG(amount) FROM payment GROUP BY customer_id", engine)

     customer_id  AVG(amount)
0              1     3.708750
1              2     4.767778
2              3     5.220769
3              4     3.717273
4              5     3.805789
..           ...          ...
594          595     3.923333
595          596     3.454286
596          597     3.990000
597          598     3.808182
598          599     4.411053

[599 rows x 2 columns]

In [67]:
pd.read_sql("SELECT * FROM film",engine)

,film_id,title,description,release_year,language_id,original_language_id,rental_duration,rental_rate,length,replacement_cost,rating,special_features,last_update
0,1,ACADEMY DINOSAUR,A Epic Drama of a Feminist And a Mad Scientist...,2006,1,None,6,0.99,86,20.99,PG,"Deleted Scenes,Behind the Scenes",2006-02-15 05:03:42
1,2,ACE GOLDFINGER,A Astounding Epistle of a Database Administrat...,2006,1,None,3,4.99,48,12.99,G,"Trailers,Deleted Scenes",2006-02-15 05:03:42
2,3,ADAPTATION HOLES,A Astounding Reflection of a Lumberjack And a ...,2006,1,None,7,2.99,50,18.99,NC-17,"Trailers,Deleted Scenes",2006-02-15 05:03:42
3,4,AFFAIR PREJUDICE,A Fanciful Documentary of a Frisbee And a Lumb...,2006,1,None,5,2.99,117,26.99,G,"Commentaries,Behind the Scenes",2006-02-15 05:03:42
4,5,AFRICAN EGG,A Fast-Paced Documentary of a Pastry Chef And ...,2006,1,None,6,2.99,130,22.99,G,Deleted Scenes,2006-02-15 05:03:42
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,YOUNG LANGUAGE,A Unbelieveable Yarn of a Boat And a Database ...,2006,1,None,6,0.99,183,9.99,G,"Trailers,Behind the Scenes",2006-02-15 05:03:42
996,997,YOUTH KICK,A Touching Drama of a Teacher And a Cat who mu...,2006,1,None,4,0.99,179,14.99,NC-17,"Trailers,Behind the Scenes",2006-02-15 05:03:42
997,998,ZHIVAGO CORE,A Fateful Yarn of a Composer And a Man who mus...,2006,1,None,6,0.99,105,10.99,NC-17,Deleted Scenes,2006-02-15 05:03:42
998,999,ZOOLANDER FICTION,A Fateful Reflection of a Waitress And a Boat ...,2006,1,None,5,2.99,101,28.99,R,"Trailers,Deleted Scenes",2006-02-15 05:03:42
999,1000,ZORRO ARK,A Intrepid Panorama of a Mad Scientist And a B...,2006,1,None,3,4.99,50,18.99,NC-17,"Trailers,Commentaries,Behind the Scenes",2006-02-15 05:03:42

In [68]:
#Ratings con más de 200 películas
pd.read_sql("SELECT COUNT(*), rating FROM film GROUP BY rating HAVING COUNT(*)>200",engine)

   COUNT(*) rating
0       210  NC-17
1       223  PG-13

In [69]:
pd.read_sql("SELECT * FROM payment",engine)

,payment_id,customer_id,staff_id,rental_id,amount,payment_date,last_update
0,1,1,1,76,2.99,2005-05-25 11:30:37,2006-02-15 22:12:30
1,2,1,1,573,0.99,2005-05-28 10:35:23,2006-02-15 22:12:30
2,3,1,1,1185,5.99,2005-06-15 00:54:12,2006-02-15 22:12:30
3,4,1,2,1422,0.99,2005-06-15 18:02:53,2006-02-15 22:12:30
4,5,1,2,1476,9.99,2005-06-15 21:08:46,2006-02-15 22:12:30
...,...,...,...,...,...,...,...
16039,16045,599,1,14599,4.99,2005-08-21 17:43:42,2006-02-15 22:24:12
16040,16046,599,1,14719,1.99,2005-08-21 21:41:57,2006-02-15 22:24:12
16041,16047,599,2,15590,8.99,2005-08-23 06:09:44,2006-02-15 22:24:12
16042,16048,599,2,15719,2.99,2005-08-23 11:08:46,2006-02-15 22:24:13
16043,16049,599,2,15725,2.99,2005-08-23 11:25:00,2006-02-15 22:24:13

In [70]:
pd.read_sql("SELECT customer_id, SUM(amount) AS suma FROM payment GROUP BY customer_id HAVING suma>150 ",engine)

    customer_id    suma
0             7  151.67
1            21  155.65
2            26  152.66
3            50  169.65
4            75  155.59
5           119  153.66
6           137  194.61
7           144  195.58
8           148  216.54
9           176  173.63
10          178  194.61
11          181  174.66
12          187  159.72
13          196  151.65
14          197  154.60
15          209  161.68
16          211  151.66
17          236  175.58
18          257  151.63
19          259  168.68
20          267  159.64
21          273  157.65
22          274  152.65
23          293  158.69
24          295  162.62
25          346  155.68
26          360  150.66
27          366  152.63
28          368  157.65
29          372  158.66
30          373  161.65
31          390  152.67
32          403  166.65
33          410  167.62
34          439  151.64
35          454  151.67
36          459  186.62
37          462  159.67
38          468  175.61
39          469  177.60
40          470  160.68
41          506  152.65
42          522  167.67
43          526  221.55
44          532  152.68
45          550  159.68

In [71]:
pd.read_sql("SELECT * FROM actor",engine)

     actor_id first_name     last_name         last_update
0           1   PENELOPE       GUINESS 2006-02-15 04:34:33
1           2       NICK      WAHLBERG 2006-02-15 04:34:33
2           3         ED         CHASE 2006-02-15 04:34:33
3           4   JENNIFER         DAVIS 2006-02-15 04:34:33
4           5     JOHNNY  LOLLOBRIGIDA 2006-02-15 04:34:33
..        ...        ...           ...                 ...
195       196       BELA        WALKEN 2006-02-15 04:34:33
196       197      REESE          WEST 2006-02-15 04:34:33
197       198       MARY        KEITEL 2006-02-15 04:34:33
198       199      JULIA       FAWCETT 2006-02-15 04:34:33
199       200      THORA        TEMPLE 2006-02-15 04:34:33

[200 rows x 4 columns]

In [72]:
pd.read_sql("SELECT * FROM film_actor",engine)

      actor_id  film_id         last_update
0            1        1 2006-02-15 05:05:03
1            1       23 2006-02-15 05:05:03
2            1       25 2006-02-15 05:05:03
3            1      106 2006-02-15 05:05:03
4            1      140 2006-02-15 05:05:03
...        ...      ...                 ...
5457       200      879 2006-02-15 05:05:03
5458       200      912 2006-02-15 05:05:03
5459       200      945 2006-02-15 05:05:03
5460       200      958 2006-02-15 05:05:03
5461       200      993 2006-02-15 05:05:03

[5462 rows x 3 columns]

In [73]:
pd.read_sql("SELECT * FROM payment",engine)

,payment_id,customer_id,staff_id,rental_id,amount,payment_date,last_update
0,1,1,1,76,2.99,2005-05-25 11:30:37,2006-02-15 22:12:30
1,2,1,1,573,0.99,2005-05-28 10:35:23,2006-02-15 22:12:30
2,3,1,1,1185,5.99,2005-06-15 00:54:12,2006-02-15 22:12:30
3,4,1,2,1422,0.99,2005-06-15 18:02:53,2006-02-15 22:12:30
4,5,1,2,1476,9.99,2005-06-15 21:08:46,2006-02-15 22:12:30
...,...,...,...,...,...,...,...
16039,16045,599,1,14599,4.99,2005-08-21 17:43:42,2006-02-15 22:24:12
16040,16046,599,1,14719,1.99,2005-08-21 21:41:57,2006-02-15 22:24:12
16041,16047,599,2,15590,8.99,2005-08-23 06:09:44,2006-02-15 22:24:12
16042,16048,599,2,15719,2.99,2005-08-23 11:08:46,2006-02-15 22:24:13
16043,16049,599,2,15725,2.99,2005-08-23 11:25:00,2006-02-15 22:24:13

In [74]:
pd.read_sql("SELECT * FROM film",engine)

,film_id,title,description,release_year,language_id,original_language_id,rental_duration,rental_rate,length,replacement_cost,rating,special_features,last_update
0,1,ACADEMY DINOSAUR,A Epic Drama of a Feminist And a Mad Scientist...,2006,1,None,6,0.99,86,20.99,PG,"Deleted Scenes,Behind the Scenes",2006-02-15 05:03:42
1,2,ACE GOLDFINGER,A Astounding Epistle of a Database Administrat...,2006,1,None,3,4.99,48,12.99,G,"Trailers,Deleted Scenes",2006-02-15 05:03:42
2,3,ADAPTATION HOLES,A Astounding Reflection of a Lumberjack And a ...,2006,1,None,7,2.99,50,18.99,NC-17,"Trailers,Deleted Scenes",2006-02-15 05:03:42
3,4,AFFAIR PREJUDICE,A Fanciful Documentary of a Frisbee And a Lumb...,2006,1,None,5,2.99,117,26.99,G,"Commentaries,Behind the Scenes",2006-02-15 05:03:42
4,5,AFRICAN EGG,A Fast-Paced Documentary of a Pastry Chef And ...,2006,1,None,6,2.99,130,22.99,G,Deleted Scenes,2006-02-15 05:03:42
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,YOUNG LANGUAGE,A Unbelieveable Yarn of a Boat And a Database ...,2006,1,None,6,0.99,183,9.99,G,"Trailers,Behind the Scenes",2006-02-15 05:03:42
996,997,YOUTH KICK,A Touching Drama of a Teacher And a Cat who mu...,2006,1,None,4,0.99,179,14.99,NC-17,"Trailers,Behind the Scenes",2006-02-15 05:03:42
997,998,ZHIVAGO CORE,A Fateful Yarn of a Composer And a Man who mus...,2006,1,None,6,0.99,105,10.99,NC-17,Deleted Scenes,2006-02-15 05:03:42
998,999,ZOOLANDER FICTION,A Fateful Reflection of a Waitress And a Boat ...,2006,1,None,5,2.99,101,28.99,R,"Trailers,Deleted Scenes",2006-02-15 05:03:42
999,1000,ZORRO ARK,A Intrepid Panorama of a Mad Scientist And a B...,2006,1,None,3,4.99,50,18.99,NC-17,"Trailers,Commentaries,Behind the Scenes",2006-02-15 05:03:42

In [75]:
#Cantidad de películas por language_id.
pd.read_sql("SELECT language_id, COUNT(film_id) FROM film GROUP BY language_id",engine)

   language_id  COUNT(film_id)
0            1            1000

In [76]:
pd.read_sql("SELECT * FROM customer",engine)

,customer_id,store_id,first_name,last_name,email,address_id,active,create_date,last_update
0,1,1,MARY,SMITH,MARY.SMITH@sakilacustomer.org,5,1,2006-02-14 22:04:36,2006-02-15 04:57:20
1,2,1,PATRICIA,JOHNSON,PATRICIA.JOHNSON@sakilacustomer.org,6,1,2006-02-14 22:04:36,2006-02-15 04:57:20
2,3,1,LINDA,WILLIAMS,LINDA.WILLIAMS@sakilacustomer.org,7,1,2006-02-14 22:04:36,2006-02-15 04:57:20
3,4,2,BARBARA,JONES,BARBARA.JONES@sakilacustomer.org,8,1,2006-02-14 22:04:36,2006-02-15 04:57:20
4,5,1,ELIZABETH,BROWN,ELIZABETH.BROWN@sakilacustomer.org,9,1,2006-02-14 22:04:36,2006-02-15 04:57:20
...,...,...,...,...,...,...,...,...,...
594,595,1,TERRENCE,GUNDERSON,TERRENCE.GUNDERSON@sakilacustomer.org,601,1,2006-02-14 22:04:37,2006-02-15 04:57:20
595,596,1,ENRIQUE,FORSYTHE,ENRIQUE.FORSYTHE@sakilacustomer.org,602,1,2006-02-14 22:04:37,2006-02-15 04:57:20
596,597,1,FREDDIE,DUGGAN,FREDDIE.DUGGAN@sakilacustomer.org,603,1,2006-02-14 22:04:37,2006-02-15 04:57:20
597,598,1,WADE,DELVALLE,WADE.DELVALLE@sakilacustomer.org,604,1,2006-02-14 22:04:37,2006-02-15 04:57:20
598,599,2,AUSTIN,CINTRON,AUSTIN.CINTRON@sakilacustomer.org,605,1,2006-02-14 22:04:37,2006-02-15 04:57:20

In [77]:
pd.read_sql("SELECT * FROM address",engine)

,address_id,address,address2,district,city_id,postal_code,phone,location,last_update
0,1,47 MySakila Drive,NaN,Alberta,300,,,b'\x00\x00\x00\x00\x01\x01\x00\x00\x00>\n2]c4\...,2014-09-25 22:30:27
1,2,28 MySQL Boulevard,NaN,QLD,576,,,b'\x00\x00\x00\x00\x01\x01\x00\x00\x00\x8e\x10...,2014-09-25 22:30:09
2,3,23 Workhaven Lane,NaN,Alberta,300,,14033335568,b'\x00\x00\x00\x00\x01\x01\x00\x00\x00\xcd\xc4...,2014-09-25 22:30:27
3,4,1411 Lillydale Drive,NaN,QLD,576,,6172235589,b'\x00\x00\x00\x00\x01\x01\x00\x00\x00[\r\xe44...,2014-09-25 22:30:09
4,5,1913 Hanoi Way,,Nagasaki,463,35200,28303384290,b'\x00\x00\x00\x00\x01\x01\x00\x00\x00(\xd17\x...,2014-09-25 22:31:53
...,...,...,...,...,...,...,...,...,...
598,601,844 Bucuresti Place,,Liaoning,242,36603,935952366111,b'\x00\x00\x00\x00\x01\x01\x00\x00\x00\xb8\x80...,2014-09-25 22:30:37
599,602,1101 Bucuresti Boulevard,,West Greece,401,97661,199514580428,b'\x00\x00\x00\x00\x01\x01\x00\x00\x00\xaa\xc1...,2014-09-25 22:31:07
600,603,1103 Quilmes Boulevard,,Piura,503,52137,644021380889,b'\x00\x00\x00\x00\x01\x01\x00\x00\x00\xad\x96...,2014-09-25 22:32:34
601,604,1331 Usak Boulevard,,Vaud,296,61960,145308717464,"b""\x00\x00\x00\x00\x01\x01\x00\x00\x00\xce'<\x...",2014-09-25 22:33:14
602,605,1325 Fukuyama Street,,Heilongjiang,537,27107,288241215394,b'\x00\x00\x00\x00\x01\x01\x00\x00\x00\x17T\np...,2014-09-25 22:30:44

In [78]:
pd.read_sql("SELECT * FROM city",engine)

     city_id                  city  country_id         last_update
0          1  A Coruña (La Coruña)          87 2006-02-15 04:45:25
1          2                  Abha          82 2006-02-15 04:45:25
2          3             Abu Dhabi         101 2006-02-15 04:45:25
3          4                 Acuña          60 2006-02-15 04:45:25
4          5                 Adana          97 2006-02-15 04:45:25
..       ...                   ...         ...                 ...
595      596                 Zaria          69 2006-02-15 04:45:25
596      597          Zeleznogorsk          80 2006-02-15 04:45:25
597      598           Zhezqazghan          51 2006-02-15 04:45:25
598      599              Zhoushan          23 2006-02-15 04:45:25
599      600            Ziguinchor          83 2006-02-15 04:45:25

[600 rows x 4 columns]

In [79]:
pd.read_sql("SELECT * FROM country", engine)

     country_id               country         last_update
0             1           Afghanistan 2006-02-15 04:44:00
1             2               Algeria 2006-02-15 04:44:00
2             3        American Samoa 2006-02-15 04:44:00
3             4                Angola 2006-02-15 04:44:00
4             5              Anguilla 2006-02-15 04:44:00
..          ...                   ...                 ...
104         105               Vietnam 2006-02-15 04:44:00
105         106  Virgin Islands, U.S. 2006-02-15 04:44:00
106         107                 Yemen 2006-02-15 04:44:00
107         108            Yugoslavia 2006-02-15 04:44:00
108         109                Zambia 2006-02-15 04:44:00

[109 rows x 3 columns]

## JOINS

In [80]:
# pd.read_sql("SELECT * FROM clientes c LEFT JOIN pedidos AS p ON c.`CÓDIGOCLIENTE`=p.`CÓDIGO CLIENTE` WHERE POBLACIÓN = 'MADRID' AND p.`CÓDIGO CLIENTE` IS NULL ",engine)
# pd.read_sql("SELECT * FROM clientes_access c INNER JOIN pedidos_access p ON c.`CÓDIGOCLIENTE`=p.`CÓDIGO CLIENTE` WHERE POBLACIÓN = 'MADRID' ORDER BY CÓDIGOCLIENTE",engine)

In [81]:
pd.read_sql("SELECT first_name, last_name, address FROM customer INNER JOIN address ON customer.address_id=	address.address_id ",engine)

    first_name  last_name                   address
0         MARY      SMITH            1913 Hanoi Way
1     PATRICIA    JOHNSON          1121 Loja Avenue
2        LINDA   WILLIAMS         692 Joliet Street
3      BARBARA      JONES         1566 Inegöl Manor
4    ELIZABETH      BROWN           53 Idfu Parkway
..         ...        ...                       ...
594   TERRENCE  GUNDERSON       844 Bucuresti Place
595    ENRIQUE   FORSYTHE  1101 Bucuresti Boulevard
596    FREDDIE     DUGGAN    1103 Quilmes Boulevard
597       WADE   DELVALLE       1331 Usak Boulevard
598     AUSTIN    CINTRON      1325 Fukuyama Street

[599 rows x 3 columns]

3. Clientes con ciudad y país

Muestra:

nombre completo del cliente

dirección

ciudad

país

Tablas: customer + address + city + country

In [82]:
pd.read_sql("SELECT first_name, last_name, address, city FROM customer JOIN address ON customer.address_id=address.address_id JOIN city ON address.city_id=city.city_id",engine)

    first_name  last_name                   address            city
0         MARY      SMITH            1913 Hanoi Way          Sasebo
1     PATRICIA    JOHNSON          1121 Loja Avenue  San Bernardino
2        LINDA   WILLIAMS         692 Joliet Street         Athenai
3      BARBARA      JONES         1566 Inegöl Manor        Myingyan
4    ELIZABETH      BROWN           53 Idfu Parkway          Nantou
..         ...        ...                       ...             ...
594   TERRENCE  GUNDERSON       844 Bucuresti Place         Jinzhou
595    ENRIQUE   FORSYTHE  1101 Bucuresti Boulevard          Patras
596    FREDDIE     DUGGAN    1103 Quilmes Boulevard         Sullana
597       WADE   DELVALLE       1331 Usak Boulevard        Lausanne
598     AUSTIN    CINTRON      1325 Fukuyama Street           Tieli

[599 rows x 4 columns]

4. Películas con idioma

Muestra:

title

language.name

Tablas: film + language

In [83]:
pd.read_sql("SELECT title FROM film", engine)

                 title
0     ACADEMY DINOSAUR
1       ACE GOLDFINGER
2     ADAPTATION HOLES
3     AFFAIR PREJUDICE
4          AFRICAN EGG
..                 ...
995     YOUNG LANGUAGE
996         YOUTH KICK
997       ZHIVAGO CORE
998  ZOOLANDER FICTION
999          ZORRO ARK

[1000 rows x 1 columns]

In [84]:
pd.read_sql("SELECT title, name FROM film JOIN language",engine)

                 title      name
0     ACADEMY DINOSAUR    German
1     ACADEMY DINOSAUR    French
2     ACADEMY DINOSAUR  Mandarin
3     ACADEMY DINOSAUR  Japanese
4     ACADEMY DINOSAUR   Italian
...                ...       ...
5995         ZORRO ARK    French
5996         ZORRO ARK  Mandarin
5997         ZORRO ARK  Japanese
5998         ZORRO ARK   Italian
5999         ZORRO ARK   English

[6000 rows x 2 columns]

5. Empleados con tienda

Muestra:

nombre del empleado

id de la tienda donde trabaja

Tablas: staff + store

In [85]:
pd.read_sql("SELECT * FROM staff",engine)

,staff_id,first_name,last_name,address_id,picture,email,store_id,active,username,password,last_update
0,1,Mike,Hillyer,3,b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\...,Mike.Hillyer@sakilastaff.com,1,1,Mike,8cb2237d0679ca88db6464eac60da96345513964,2006-02-15 03:57:16
1,2,Jon,Stephens,4,None,Jon.Stephens@sakilastaff.com,2,1,Jon,NaN,2006-02-15 03:57:16

In [86]:
pd.read_sql("SELECT * FROM store",engine)

   store_id  manager_staff_id  address_id         last_update
0         1                 1           1 2006-02-15 04:57:12
1         2                 2           2 2006-02-15 04:57:12

In [93]:
pd.read_sql("SELECT first_name, last_name, store.store_id FROM staff JOIN store ON staff.staff_id = store.manager_staff_id",engine)

  first_name last_name  store_id
0       Mike   Hillyer         1
1        Jon  Stephens         2