## Importacion de librerias y acceso a contenedor sql

In [1]:
import os
import pandas as pd
from dotenv import load_dotenv
from sqlalchemy import create_engine

load_dotenv("credenciales/practica.env")

host = os.getenv("MYSQL_HOST", "127.0.0.1")
port = os.getenv("MYSQL_PORT", "3306")
db = os.getenv("MYSQL_DB", "practica_ejercicios")

user = os.getenv("MYSQL_USER")
pwd  = os.getenv("MYSQL_PASSWORD")  # SOLO esta


engine = create_engine(f"mysql+pymysql://{user}:{pwd}@{host}:{port}/{db}")

In [2]:
print("MYSQL_DB existe?:", os.getenv("MYSQL_DB"))

MYSQL_DB existe?: practica_ejercicios

In [3]:
print("cwd:", os.getcwd())
print("MYSQL_USER:", os.getenv("MYSQL_USER"))
print("MYSQL_PASSWORD existe?:", os.getenv("MYSQL_PASSWORD") is not None)

cwd: c:\Users\workw\Documents\practicar programacion\sql
MYSQL_USER: usuario_practica
MYSQL_PASSWORD existe?: True

## Leer ODS y guardar en MySQL

In [4]:
# Leer ODS desde tu PC (ruta local)
df_clientes = pd.read_excel("Video2/CLIENTES.ods", engine="odf")
df_productos = pd.read_excel("Video2/PRODUCTOS1.ods", engine="odf")
df_productos_nuevos = pd.read_excel("Video2/ProductosNuevos.ods",engine="odf")

df_clientes1 = pd.read_csv("Video2/CLIENTES1.csv")
df_pedidos1 = pd.read_csv("Video2/PEDIDOS1.csv")
df_productos_pedidos1 = pd.read_csv("Video2/PRODUCTOS-PEDIDOS1.csv")
df_productos2 = pd.read_csv("Video2/PRODUCTOS2.csv")
df_pedidos = pd.read_excel("Video2/PEDIDOS.ods",engine="odf")

In [5]:
# Guardar a MySQL
df_clientes.to_sql("clientes", engine, if_exists="replace", index=False)
df_productos.to_sql("productos", engine, if_exists="replace", index=False)
df_productos_nuevos.to_sql("ProductosNuevos",engine,if_exists="replace",index=False)

df_clientes1.to_sql("clientes_access",engine,if_exists="replace",index=False)
df_pedidos1.to_sql("pedidos_access",engine,if_exists="replace",index=False)
df_productos_pedidos1.to_sql("productos_pedidos_access",engine,if_exists="replace",index=False)
df_productos2.to_sql("productos_access",engine,if_exists="replace",index=False)
df_pedidos.to_sql("pedidos", engine,if_exists="replace",index=False)

52

## Ejercicios

### Comandos SQL
- DDL: (Data Definition Language o Lenguaje de Definición de Datos), en PostgreSQL se utilizan para definir, modificar y eliminar la estructura de los objetos de la base de datos, como tablas, índices y esquemas. PostgreSQL destaca porque sus comandos DDL son transaccionales, lo que significa que puedes ejecutarlos dentro de un bloque BEGIN ... COMMIT y revertirlos con ROLLBACK si algo falla.
- DML: (Data Manipulation Language o Lenguaje de Manipulación de Datos) en PostgreSQL se utilizan para gestionar los datos que viven dentro de las tablas. A diferencia del DDL (que cambia la estructura), el DML afecta a las filas de información.
- DCL: (Data Control Language o Lenguaje de Control de Datos) se utilizan para gestionar la seguridad de la base de datos, permitiendo a los administradores otorgar o retirar permisos a los usuarios y roles sobre objetos específicos.
- TCL: (Transaction Control Language o Lenguaje de Control de Transacciones) se utilizan para gestionar los cambios realizados por los comandos DML, Su función principal es agrupar varias operaciones en una sola unidad de trabajo para asegurar la integridad de los datos, En PostgreSQL, si no abres una transacción explícita, cada comando se ejecuta en modo "autocommit" (se guarda automáticamente).

Para DDL
- CREATE: Se utiliza para crear nuevos objetos (tablas, índices, vistas, funciones, etc.)
-

### SELECT, FROM, WHERE

In [6]:
pd.read_sql("SHOW TABLES;", engine)

  Tables_in_practica_ejercicios
0               ProductosNuevos
1                      clientes
2               clientes_access
3                       pedidos
4                pedidos_access
5                     productos
6              productos_access
7      productos_pedidos_access

In [7]:
pd.read_sql("DESCRIBE productos;", engine)

            Field        Type Null Key Default Extra
0  CÓDIGOARTÍCULO        text  YES        None
1         SECCIÓN        text  YES        None
2  NOMBREARTÍCULO        text  YES        None
3          PRECIO      double  YES        None
4           FECHA    datetime  YES        None
5       IMPORTADO  tinyint(1)  YES        None
6    PAÍSDEORIGEN        text  YES        None
7            FOTO      double  YES        None

In [8]:
pd.read_sql("SELECT * FROM productos;", engine)

,CÓDIGOARTÍCULO,SECCIÓN,NOMBREARTÍCULO,PRECIO,FECHA,IMPORTADO,PAÍSDEORIGEN,FOTO
0,AR01,FERRETERÍA,DESTORNILLADOR,6.6280,2000-10-22,0,ESPAÑA,None
1,AR02,CONFECCIÓN,TRAJE CABALLERO,284.5769,2002-03-11,0,ITALIA,None
2,AR03,JUGUETERÍA,COCHE TELEDIRIGIDO,159.4462,2002-05-26,0,MARRUECOS,None
3,AR04,DEPORTES,RAQUETA TENIS,93.4694,2000-03-20,0,USA,None
4,AR06,DEPORTES,MANCUERNAS,60.0000,2000-09-13,0,USA,None
5,AR07,CONFECCIÓN,SERRUCHO,30.2045,2001-03-23,0,FRANCIA,None
6,AR08,JUGUETERÍA,CORREPASILLOS,103.3356,2000-04-11,0,JAPÓN,None
7,AR09,CONFECCIÓN,PANTALÓN SEÑORA,174.2310,2000-01-10,0,MARRUECOS,None
8,AR10,JUGUETERÍA,CONSOLA VIDEO,442.5444,2002-09-24,0,USA,None
9,AR11,CERÁMICA,TUBOS,168.4253,2000-02-04,0,CHINA,None
10,AR12,FERRETERÍA,LLAVE INGLESA,24.3986,2001-05-23,0,USA,None
11,AR13,CONFECCIÓN,CAMISA CABALLERO,67.1306,2002-08-11,0,ESPAÑA,None
12,AR14,JUGUETERÍA,TREN ELÉCTRICO,1505.3766,2001-07-03,0,JAPÓN,None
13,AR15,CERÁMICA,PLATO DECORATIVO,54.0911,2000-06-07,0,CHINA,None
14,AR16,FERRETERÍA,ALICATES,6.7362,2000-04-17,0,ITALIA,None
15,AR17,JUGUETERÍA,MUÑECA ANDADORA,105.0593,2001-01-04,0,ESPAÑA,None
16,AR18,DEPORTES,PISTOLA OLÍMPICA,46.7347,2001-02-02,0,SUECIA,None
17,AR19,CONFECCIÓN,BLUSA SRA.,101.0566,2000-03-18,0,CHINA,None
18,AR20,CERÁMICA,JUEGO DE TE,43.2728,2001-01-15,0,CHINA,None
19,AR21,CERÁMICA,CENICERO,19.7468,2001-07-02,0,JAPÓN,None
20,AR22,FERRETERÍA,MARTILLO,11.3952,2001-09-04,0,ESPAÑA,None
21,AR23,CONFECCIÓN,CAZADORA PIEL,522.6930,2001-07-10,0,ITALIA,None
22,AR24,DEPORTES,BALÓN RUGBY,111.6440,2000-11-11,0,USA,None
23,AR25,DEPORTES,BALÓN BALONCESTO,75.2731,2001-06-25,0,JAPÓN,None
24,AR26,JUGUETERÍA,FUERTE DE SOLDADOS,143.7020,2000-11-25,0,JAPÓN,None
25,AR27,CONFECCIÓN,ABRIGO CABALLERO,500000.0000,2002-04-05,0,ITALIA,None
26,AR28,DEPORTES,BALÓN FÚTBOL,43.9147,2002-07-04,0,ESPAÑA,None
27,AR29,CONFECCIÓN,ABRIGO SRA,360.0736,2001-05-03,0,MARRUECOS,None
28,AR30,FERRETERÍA,DESTORNILLADOR,9.0584,2002-02-20,0,FRANCIA,None
29,AR31,JUGUETERÍA,PISTOLA CON SONIDOS,57.2500,2001-04-15,0,ESPAÑA,None
30,AR32,DEPORTES,CRONÓMETRO,439.1764,2002-01-03,0,USA,None
31,AR33,CERÁMICA,MACETA,29.0434,2000-02-23,0,ESPAÑA,None
32,AR34,OFICINA,PIE DE LÁMPARA,39.7606,2001-05-27,0,TURQUÍA,None
33,AR35,FERRETERÍA,LIMA GRANDE,22.0692,2002-08-10,0,ESPAÑA,None
34,AR36,FERRETERÍA,JUEGO DE BROCAS,15.0950,2002-07-04,0,TAIWÁN,None
35,AR37,CONFECCIÓN,CINTURÓN DE PIEL,4.3273,2002-05-12,0,ESPAÑA,None
36,AR38,DEPORTES,CAÑA DE PESCA,270.0000,2000-02-14,0,USA,None
37,AR39,CERÁMICA,JARRA CHINA,127.7704,2002-09-02,0,CHINA,None
38,AR40,DEPORTES,BOTA ALPINISMO,144.0000,2002-05-05,0,ESPAÑA,None
39,AR41,DEPORTES,PALAS DE PING PONG,21.6000,2002-02-02,0,ESPAÑA,None

In [9]:
pd.read_sql("SELECT nombreartículo, precio, paísdeorigen FROM productos WHERE PAÍSDEORIGEN = 'españa' OR PRECIO >350;", engine)

         nombreartículo       precio paísdeorigen
0        DESTORNILLADOR       6.6280       ESPAÑA
1         CONSOLA VIDEO     442.5444          USA
2      CAMISA CABALLERO      67.1306       ESPAÑA
3        TREN ELÉCTRICO    1505.3766        JAPÓN
4       MUÑECA ANDADORA     105.0593       ESPAÑA
5              MARTILLO      11.3952       ESPAÑA
6         CAZADORA PIEL     522.6930       ITALIA
7      ABRIGO CABALLERO  500000.0000       ITALIA
8          BALÓN FÚTBOL      43.9147       ESPAÑA
9            ABRIGO SRA     360.0736    MARRUECOS
10  PISTOLA CON SONIDOS      57.2500       ESPAÑA
11           CRONÓMETRO     439.1764          USA
12               MACETA      29.0434       ESPAÑA
13          LIMA GRANDE      22.0692       ESPAÑA
14     CINTURÓN DE PIEL       4.3273       ESPAÑA
15       BOTA ALPINISMO     144.0000       ESPAÑA
16   PALAS DE PING PONG      21.6000       ESPAÑA

#### Nota: en select y FROM, no importa las mayusculas pero despues de WHERE si importan, mejor escribir todo en mayusculas y no olvidar las tildes, los comandos de sql no importan las mayusculas

### Order by

In [10]:
pd.read_sql("SELECT SECCIÓN, NOMBREARTÍCULO FROM productos WHERE SECCIÓN = 'deportes' OR SECCIÓN= 'cerámica' ORDER BY SECCIÓN;", engine)

     SECCIÓN      NOMBREARTÍCULO
0   CERÁMICA               TUBOS
1   CERÁMICA    PLATO DECORATIVO
2   CERÁMICA         JUEGO DE TE
3   CERÁMICA            CENICERO
4   CERÁMICA              MACETA
5   CERÁMICA         JARRA CHINA
6   DEPORTES       RAQUETA TENIS
7   DEPORTES          MANCUERNAS
8   DEPORTES    PISTOLA OLÍMPICA
9   DEPORTES         BALÓN RUGBY
10  DEPORTES    BALÓN BALONCESTO
11  DEPORTES        BALÓN FÚTBOL
12  DEPORTES          CRONÓMETRO
13  DEPORTES       CAÑA DE PESCA
14  DEPORTES      BOTA ALPINISMO
15  DEPORTES  PALAS DE PING PONG

In [11]:
pd.read_sql("SELECT SECCIÓN, NOMBREARTÍCULO FROM productos WHERE SECCIÓN = 'deportes' OR SECCIÓN= 'cerámica' ORDER BY SECCIÓN DESC;", engine)

     SECCIÓN      NOMBREARTÍCULO
0   DEPORTES       RAQUETA TENIS
1   DEPORTES          MANCUERNAS
2   DEPORTES    PISTOLA OLÍMPICA
3   DEPORTES         BALÓN RUGBY
4   DEPORTES    BALÓN BALONCESTO
5   DEPORTES        BALÓN FÚTBOL
6   DEPORTES          CRONÓMETRO
7   DEPORTES       CAÑA DE PESCA
8   DEPORTES      BOTA ALPINISMO
9   DEPORTES  PALAS DE PING PONG
10  CERÁMICA               TUBOS
11  CERÁMICA    PLATO DECORATIVO
12  CERÁMICA         JUEGO DE TE
13  CERÁMICA            CENICERO
14  CERÁMICA              MACETA
15  CERÁMICA         JARRA CHINA

#### Nota: DESC al lado derecho de la variable la hace decendente

In [12]:
pd.read_sql("SELECT SECCIÓN, NOMBREARTÍCULO FROM productos WHERE SECCIÓN = 'deportes' OR SECCIÓN= 'cerámica' ORDER BY SECCIÓN ASC;", engine)

     SECCIÓN      NOMBREARTÍCULO
0   CERÁMICA               TUBOS
1   CERÁMICA    PLATO DECORATIVO
2   CERÁMICA         JUEGO DE TE
3   CERÁMICA            CENICERO
4   CERÁMICA              MACETA
5   CERÁMICA         JARRA CHINA
6   DEPORTES       RAQUETA TENIS
7   DEPORTES          MANCUERNAS
8   DEPORTES    PISTOLA OLÍMPICA
9   DEPORTES         BALÓN RUGBY
10  DEPORTES    BALÓN BALONCESTO
11  DEPORTES        BALÓN FÚTBOL
12  DEPORTES          CRONÓMETRO
13  DEPORTES       CAÑA DE PESCA
14  DEPORTES      BOTA ALPINISMO
15  DEPORTES  PALAS DE PING PONG

#### 1. Ordena todos los productos por precio (de menor a mayor)

In [13]:
pd.read_sql("SELECT NOMBREARTÍCULO, PRECIO FROM productos ORDER BY NOMBREARTÍCULO ASC", engine)

         NOMBREARTÍCULO       PRECIO
0      ABRIGO CABALLERO  500000.0000
1            ABRIGO SRA     360.0736
2              ALICATES       6.7362
3      BALÓN BALONCESTO      75.2731
4          BALÓN FÚTBOL      43.9147
5           BALÓN RUGBY     111.6440
6            BLUSA SRA.     101.0566
7        BOTA ALPINISMO     144.0000
8      CAMISA CABALLERO      67.1306
9         CAÑA DE PESCA     270.0000
10        CAZADORA PIEL     522.6930
11             CENICERO      19.7468
12     CINTURÓN DE PIEL       4.3273
13   COCHE TELEDIRIGIDO     159.4462
14        CONSOLA VIDEO     442.5444
15        CORREPASILLOS     103.3356
16           CRONÓMETRO     439.1764
17       DESTORNILLADOR       6.6280
18       DESTORNILLADOR       9.0584
19   FUERTE DE SOLDADOS     143.7020
20          JARRA CHINA     127.7704
21      JUEGO DE BROCAS      15.0950
22          JUEGO DE TE      43.2728
23          LIMA GRANDE      22.0692
24        LLAVE INGLESA      24.3986
25               MACETA      29.0434
26           MANCUERNAS      60.0000
27             MARTILLO      11.3952
28      MUÑECA ANDADORA     105.0593
29   PALAS DE PING PONG      21.6000
30      PANTALÓN SEÑORA     174.2310
31       PIE DE LÁMPARA      39.7606
32  PISTOLA CON SONIDOS      57.2500
33     PISTOLA OLÍMPICA      46.7347
34     PLATO DECORATIVO      54.0911
35        RAQUETA TENIS      93.4694
36             SERRUCHO      30.2045
37      TRAJE CABALLERO     284.5769
38       TREN ELÉCTRICO    1505.3766
39                TUBOS     168.4253

In [14]:
pd.read_sql("SELECT * FROM productos WHERE SECCIÓN = 'CERÁMICA' OR SECCIÓN = 'DEPORTES' ORDER BY SECCIÓN, PRECIO DESC",engine)

,CÓDIGOARTÍCULO,SECCIÓN,NOMBREARTÍCULO,PRECIO,FECHA,IMPORTADO,PAÍSDEORIGEN,FOTO
0,AR11,CERÁMICA,TUBOS,168.4253,2000-02-04,0,CHINA,None
1,AR39,CERÁMICA,JARRA CHINA,127.7704,2002-09-02,0,CHINA,None
2,AR15,CERÁMICA,PLATO DECORATIVO,54.0911,2000-06-07,0,CHINA,None
3,AR20,CERÁMICA,JUEGO DE TE,43.2728,2001-01-15,0,CHINA,None
4,AR33,CERÁMICA,MACETA,29.0434,2000-02-23,0,ESPAÑA,None
5,AR21,CERÁMICA,CENICERO,19.7468,2001-07-02,0,JAPÓN,None
6,AR32,DEPORTES,CRONÓMETRO,439.1764,2002-01-03,0,USA,None
7,AR38,DEPORTES,CAÑA DE PESCA,270.0000,2000-02-14,0,USA,None
8,AR40,DEPORTES,BOTA ALPINISMO,144.0000,2002-05-05,0,ESPAÑA,None
9,AR24,DEPORTES,BALÓN RUGBY,111.6440,2000-11-11,0,USA,None
10,AR04,DEPORTES,RAQUETA TENIS,93.4694,2000-03-20,0,USA,None
11,AR25,DEPORTES,BALÓN BALONCESTO,75.2731,2001-06-25,0,JAPÓN,None
12,AR06,DEPORTES,MANCUERNAS,60.0000,2000-09-13,0,USA,None
13,AR18,DEPORTES,PISTOLA OLÍMPICA,46.7347,2001-02-02,0,SUECIA,None
14,AR28,DEPORTES,BALÓN FÚTBOL,43.9147,2002-07-04,0,ESPAÑA,None
15,AR41,DEPORTES,PALAS DE PING PONG,21.6000,2002-02-02,0,ESPAÑA,None

In [15]:
pd.read_sql("SELECT * FROM productos WHERE SECCIÓN = 'CERÁMICA' OR SECCIÓN = 'DEPORTES' ORDER BY SECCIÓN, PAÍSDEORIGEN",engine)

,CÓDIGOARTÍCULO,SECCIÓN,NOMBREARTÍCULO,PRECIO,FECHA,IMPORTADO,PAÍSDEORIGEN,FOTO
0,AR11,CERÁMICA,TUBOS,168.4253,2000-02-04,0,CHINA,None
1,AR15,CERÁMICA,PLATO DECORATIVO,54.0911,2000-06-07,0,CHINA,None
2,AR20,CERÁMICA,JUEGO DE TE,43.2728,2001-01-15,0,CHINA,None
3,AR39,CERÁMICA,JARRA CHINA,127.7704,2002-09-02,0,CHINA,None
4,AR33,CERÁMICA,MACETA,29.0434,2000-02-23,0,ESPAÑA,None
5,AR21,CERÁMICA,CENICERO,19.7468,2001-07-02,0,JAPÓN,None
6,AR28,DEPORTES,BALÓN FÚTBOL,43.9147,2002-07-04,0,ESPAÑA,None
7,AR40,DEPORTES,BOTA ALPINISMO,144.0000,2002-05-05,0,ESPAÑA,None
8,AR41,DEPORTES,PALAS DE PING PONG,21.6000,2002-02-02,0,ESPAÑA,None
9,AR25,DEPORTES,BALÓN BALONCESTO,75.2731,2001-06-25,0,JAPÓN,None
10,AR18,DEPORTES,PISTOLA OLÍMPICA,46.7347,2001-02-02,0,SUECIA,None
11,AR04,DEPORTES,RAQUETA TENIS,93.4694,2000-03-20,0,USA,None
12,AR06,DEPORTES,MANCUERNAS,60.0000,2000-09-13,0,USA,None
13,AR24,DEPORTES,BALÓN RUGBY,111.6440,2000-11-11,0,USA,None
14,AR32,DEPORTES,CRONÓMETRO,439.1764,2002-01-03,0,USA,None
15,AR38,DEPORTES,CAÑA DE PESCA,270.0000,2000-02-14,0,USA,None

### Consultas de agrupacion

#### Funciones de agregado de SQL
- AVG: PROMEDIO
- COUNT: CONTADOR DE REGISTROS
- SUM: SUMA
- MAX: MAXIMO
- MIN: MINIMO

Necesitamos dos campos, uno para agrupar y otro para operar, por eso utilizamos el comando GROUP BY

In [16]:
pd.read_sql("SELECT SECCIÓN, SUM(PRECIO) FROM productos GROUP BY SECCIÓN;",engine)

      SECCIÓN  SUM(PRECIO)
0  FERRETERÍA      95.3806
1  CONFECCIÓN  501544.2935
2  JUGUETERÍA    2516.7141
3    DEPORTES    1305.8123
4    CERÁMICA     442.3498
5     OFICINA      39.7606

#### Nota: Se puede crear un alias

In [17]:
pd.read_sql("SELECT SECCIÓN, SUM(PRECIO) AS SUMA_ARTICULOS FROM productos GROUP BY SECCIÓN ORDER BY SUMA_ARTICULOS;",engine)

      SECCIÓN  SUMA_ARTICULOS
0     OFICINA         39.7606
1  FERRETERÍA         95.3806
2    CERÁMICA        442.3498
3    DEPORTES       1305.8123
4  JUGUETERÍA       2516.7141
5  CONFECCIÓN     501544.2935

In [18]:
# porque group by y porque no funciona asc?
pd.read_sql("SELECT SECCIÓN, AVG(PRECIO) AS MEDIA_ARTICULOS FROM productos GROUP BY SECCIÓN HAVING SECCIÓN = 'CERÁMICA' OR SECCIÓN = 'DEPORTES';",engine)

    SECCIÓN  MEDIA_ARTICULOS
0  DEPORTES       130.581230
1  CERÁMICA        73.724967

In [19]:
#### Ejercicios dejados
#1. 
pd.read_sql("DESCRIBE clientes",engine)

           Field    Type Null Key Default Extra
0  CÓDIGOCLIENTE    text  YES        None
1        EMPRESA    text  YES        None
2      DIRECCIÓN    text  YES        None
3      POBLACIÓN    text  YES        None
4       TELÉFONO  bigint  YES        None
5    RESPONSABLE    text  YES        None
6      HISTORIAL  double  YES        None

In [20]:
pd.read_sql("SELECT DIRECCIÓN, TELÉFONO, POBLACIÓN FROM clientes;",engine)

              DIRECCIÓN   TELÉFONO  POBLACIÓN
0        LAS FUENTES 78  914456435     MADRID
1         LA PALOMA 123  985323434     OVIEDO
2            MOTORES 34  934565343  BARCELONA
3           VALLECAS 34  913452378     MADRID
4          LOS MOROS 23  985754332      GIJÓN
5            AMÉRICA 45  912649987     MADRID
6             PARIS 123  933457866  BARCELONA
7       LAS FUENTES 124  942347127     BILBAO
8    PASEO DE ÁLAMOS 78  914354866     MADRID
9      VIA LAYETANA 245  936628554  BARCELONA
10     PASEO DEL MAR 45  942049586  SANTANDER
11     GENERAL PERÓN 45  981345239   A CORUÑA
12   GUZMÁN EL BUENO 45  913299475     MADRID
13        LLOBREGAT 250  939558365  BARCELONA
14         AUTONOMÍA 45  982986944       LUGO
15            CARMEN 45  980495288     ZAMORA
16         LA BAÑEZA 67  987945368       LEÓN
17        FUENCARRAL 78  913859234     MADRID
18           OLIVARES 3  953756259     MÁLAGA
19           SIERPES 78  953452567    SEVILLA
20          DIAGONAL 56  936692866  BARCELONA
21  ORTEGA Y GASSET 129  927785235     MADRID
22   INFANTA MERCEDS 23  954869234    SEVILLA
23         CASTILLA 345  976388934   ZARAGOZA
24             ORENSE 7  918459346     MADRID
25      VÍA AUGUSTA 245  933486984  BARCELONA
26          CORRIDA 345  985597315      GIJÓN
27            ATOCHA 55  912495973     MADRID
28     EL COMENDADOR 67  975694035   ZARAGOZA
29    JUAN FERNÁNDEZ 89  920268648      ÁVILA
30        LLOBREGAT 345  934587615  BARCELONA
31   CASTILLA Y LEÓN 34  915483627     MADRID
32      CASTELLANOS 205  923548965  SALAMANCA
33            ORENSE 89  916872354     MADRID
34             ANTÓN 67  978564025     TERUEL
35           MOTORES 67  935681245  BARCELONA
36          VALLECAS 45  913532785     MADRID
37     ABEL MARTÍNEZ 67  921548762  SALAMANCA

In [21]:
pd.read_sql("SELECT POBLACIÓN, COUNT(POBLACIÓN) FROM clientes GROUP BY POBLACIÓN ORDER BY COUNT(POBLACIÓN) DESC;",engine)

    POBLACIÓN  COUNT(POBLACIÓN)
0      MADRID                12
1   BARCELONA                 8
2       GIJÓN                 2
3     SEVILLA                 2
4    ZARAGOZA                 2
5   SALAMANCA                 2
6      OVIEDO                 1
7      BILBAO                 1
8   SANTANDER                 1
9    A CORUÑA                 1
10       LUGO                 1
11     ZAMORA                 1
12       LEÓN                 1
13     MÁLAGA                 1
14      ÁVILA                 1
15     TERUEL                 1

#### Lo anterior esta bien pero ignora campos en donde alguno de ellos este vacio asi que es mejor jugar con codigocliente

In [22]:
pd.read_sql("SELECT POBLACIÓN, COUNT(CÓDIGOCLIENTE) FROM clientes GROUP BY POBLACIÓN ORDER BY COUNT(POBLACIÓN) DESC;",engine)

    POBLACIÓN  COUNT(CÓDIGOCLIENTE)
0      MADRID                    12
1   BARCELONA                     8
2       GIJÓN                     2
3     SEVILLA                     2
4    ZARAGOZA                     2
5   SALAMANCA                     2
6      OVIEDO                     1
7      BILBAO                     1
8   SANTANDER                     1
9    A CORUÑA                     1
10       LUGO                     1
11     ZAMORA                     1
12       LEÓN                     1
13     MÁLAGA                     1
14      ÁVILA                     1
15     TERUEL                     1

In [23]:
pd.read_sql("SELECT * FROM productos;",engine)

,CÓDIGOARTÍCULO,SECCIÓN,NOMBREARTÍCULO,PRECIO,FECHA,IMPORTADO,PAÍSDEORIGEN,FOTO
0,AR01,FERRETERÍA,DESTORNILLADOR,6.6280,2000-10-22,0,ESPAÑA,None
1,AR02,CONFECCIÓN,TRAJE CABALLERO,284.5769,2002-03-11,0,ITALIA,None
2,AR03,JUGUETERÍA,COCHE TELEDIRIGIDO,159.4462,2002-05-26,0,MARRUECOS,None
3,AR04,DEPORTES,RAQUETA TENIS,93.4694,2000-03-20,0,USA,None
4,AR06,DEPORTES,MANCUERNAS,60.0000,2000-09-13,0,USA,None
5,AR07,CONFECCIÓN,SERRUCHO,30.2045,2001-03-23,0,FRANCIA,None
6,AR08,JUGUETERÍA,CORREPASILLOS,103.3356,2000-04-11,0,JAPÓN,None
7,AR09,CONFECCIÓN,PANTALÓN SEÑORA,174.2310,2000-01-10,0,MARRUECOS,None
8,AR10,JUGUETERÍA,CONSOLA VIDEO,442.5444,2002-09-24,0,USA,None
9,AR11,CERÁMICA,TUBOS,168.4253,2000-02-04,0,CHINA,None
10,AR12,FERRETERÍA,LLAVE INGLESA,24.3986,2001-05-23,0,USA,None
11,AR13,CONFECCIÓN,CAMISA CABALLERO,67.1306,2002-08-11,0,ESPAÑA,None
12,AR14,JUGUETERÍA,TREN ELÉCTRICO,1505.3766,2001-07-03,0,JAPÓN,None
13,AR15,CERÁMICA,PLATO DECORATIVO,54.0911,2000-06-07,0,CHINA,None
14,AR16,FERRETERÍA,ALICATES,6.7362,2000-04-17,0,ITALIA,None
15,AR17,JUGUETERÍA,MUÑECA ANDADORA,105.0593,2001-01-04,0,ESPAÑA,None
16,AR18,DEPORTES,PISTOLA OLÍMPICA,46.7347,2001-02-02,0,SUECIA,None
17,AR19,CONFECCIÓN,BLUSA SRA.,101.0566,2000-03-18,0,CHINA,None
18,AR20,CERÁMICA,JUEGO DE TE,43.2728,2001-01-15,0,CHINA,None
19,AR21,CERÁMICA,CENICERO,19.7468,2001-07-02,0,JAPÓN,None
20,AR22,FERRETERÍA,MARTILLO,11.3952,2001-09-04,0,ESPAÑA,None
21,AR23,CONFECCIÓN,CAZADORA PIEL,522.6930,2001-07-10,0,ITALIA,None
22,AR24,DEPORTES,BALÓN RUGBY,111.6440,2000-11-11,0,USA,None
23,AR25,DEPORTES,BALÓN BALONCESTO,75.2731,2001-06-25,0,JAPÓN,None
24,AR26,JUGUETERÍA,FUERTE DE SOLDADOS,143.7020,2000-11-25,0,JAPÓN,None
25,AR27,CONFECCIÓN,ABRIGO CABALLERO,500000.0000,2002-04-05,0,ITALIA,None
26,AR28,DEPORTES,BALÓN FÚTBOL,43.9147,2002-07-04,0,ESPAÑA,None
27,AR29,CONFECCIÓN,ABRIGO SRA,360.0736,2001-05-03,0,MARRUECOS,None
28,AR30,FERRETERÍA,DESTORNILLADOR,9.0584,2002-02-20,0,FRANCIA,None
29,AR31,JUGUETERÍA,PISTOLA CON SONIDOS,57.2500,2001-04-15,0,ESPAÑA,None
30,AR32,DEPORTES,CRONÓMETRO,439.1764,2002-01-03,0,USA,None
31,AR33,CERÁMICA,MACETA,29.0434,2000-02-23,0,ESPAÑA,None
32,AR34,OFICINA,PIE DE LÁMPARA,39.7606,2001-05-27,0,TURQUÍA,None
33,AR35,FERRETERÍA,LIMA GRANDE,22.0692,2002-08-10,0,ESPAÑA,None
34,AR36,FERRETERÍA,JUEGO DE BROCAS,15.0950,2002-07-04,0,TAIWÁN,None
35,AR37,CONFECCIÓN,CINTURÓN DE PIEL,4.3273,2002-05-12,0,ESPAÑA,None
36,AR38,DEPORTES,CAÑA DE PESCA,270.0000,2000-02-14,0,USA,None
37,AR39,CERÁMICA,JARRA CHINA,127.7704,2002-09-02,0,CHINA,None
38,AR40,DEPORTES,BOTA ALPINISMO,144.0000,2002-05-05,0,ESPAÑA,None
39,AR41,DEPORTES,PALAS DE PING PONG,21.6000,2002-02-02,0,ESPAÑA,None

In [24]:
# Necesitamos dos campos, uno para agrupar y otro para operar
pd.read_sql("SELECT SECCIÓN, MAX(PRECIO) FROM productos GROUP BY SECCIÓN HAVING SECCIÓN='CONFECCIÓN' ;",engine)

      SECCIÓN  MAX(PRECIO)
0  CONFECCIÓN     500000.0

In [25]:
"""
1.	Realizar una consulta sobre la tabla “Clientes”  que muestre los campos “Dirección”, “Teléfono” y “Población”. 
Este último debe aparecer en la consulta con el nombre de “Residencia”. Los registros aparecerán ordenados 
descendentemente por el campo “Población”.
"""
pd.read_sql("SELECT DIRECCIÓN, TELÉFONO, POBLACIÓN AS RESIDENCIA FROM clientes ORDER BY RESIDENCIA;",engine)

              DIRECCIÓN   TELÉFONO RESIDENCIA
0      GENERAL PERÓN 45  981345239   A CORUÑA
1     JUAN FERNÁNDEZ 89  920268648      ÁVILA
2         LLOBREGAT 345  934587615  BARCELONA
3           DIAGONAL 56  936692866  BARCELONA
4            MOTORES 67  935681245  BARCELONA
5         LLOBREGAT 250  939558365  BARCELONA
6       VÍA AUGUSTA 245  933486984  BARCELONA
7      VIA LAYETANA 245  936628554  BARCELONA
8             PARIS 123  933457866  BARCELONA
9            MOTORES 34  934565343  BARCELONA
10      LAS FUENTES 124  942347127     BILBAO
11          CORRIDA 345  985597315      GIJÓN
12         LOS MOROS 23  985754332      GIJÓN
13         LA BAÑEZA 67  987945368       LEÓN
14         AUTONOMÍA 45  982986944       LUGO
15            ATOCHA 55  912495973     MADRID
16   CASTILLA Y LEÓN 34  915483627     MADRID
17             ORENSE 7  918459346     MADRID
18            ORENSE 89  916872354     MADRID
19  ORTEGA Y GASSET 129  927785235     MADRID
20          VALLECAS 45  913532785     MADRID
21        FUENCARRAL 78  913859234     MADRID
22   GUZMÁN EL BUENO 45  913299475     MADRID
23       LAS FUENTES 78  914456435     MADRID
24   PASEO DE ÁLAMOS 78  914354866     MADRID
25           AMÉRICA 45  912649987     MADRID
26          VALLECAS 34  913452378     MADRID
27           OLIVARES 3  953756259     MÁLAGA
28        LA PALOMA 123  985323434     OVIEDO
29      CASTELLANOS 205  923548965  SALAMANCA
30     ABEL MARTÍNEZ 67  921548762  SALAMANCA
31     PASEO DEL MAR 45  942049586  SANTANDER
32   INFANTA MERCEDS 23  954869234    SEVILLA
33           SIERPES 78  953452567    SEVILLA
34             ANTÓN 67  978564025     TERUEL
35            CARMEN 45  980495288     ZAMORA
36     EL COMENDADOR 67  975694035   ZARAGOZA
37         CASTILLA 345  976388934   ZARAGOZA

In [26]:
"""
2.	Realizar una consulta que muestre que poblaciones hay en la tabla “Clientes”.
"""
pd.read_sql("SELECT POBLACIÓN AS RESIDENCIA FROM clientes GROUP BY RESIDENCIA;",engine)

   RESIDENCIA
0      MADRID
1      OVIEDO
2   BARCELONA
3       GIJÓN
4      BILBAO
5   SANTANDER
6    A CORUÑA
7        LUGO
8      ZAMORA
9        LEÓN
10     MÁLAGA
11    SEVILLA
12   ZARAGOZA
13      ÁVILA
14  SALAMANCA
15     TERUEL

In [27]:
"""
3.	Realizar una consulta de agrupación que muestre la media del precio de 
los artículos de todas las secciones. Mostrar en la consulta los campos sección y suma por sección.
"""
pd.read_sql("SELECT SECCIÓN, AVG(PRECIO), SUM(PRECIO) FROM productos GROUP BY SECCIÓN",engine)

      SECCIÓN   AVG(PRECIO)  SUM(PRECIO)
0  FERRETERÍA     13.625800      95.3806
1  CONFECCIÓN  55727.143722  501544.2935
2  JUGUETERÍA    359.530586    2516.7141
3    DEPORTES    130.581230    1305.8123
4    CERÁMICA     73.724967     442.3498
5     OFICINA     39.760600      39.7606

In [28]:
"""
4.	Realizar una consulta de agrupación que muestre la media del precio de todas las secciones 
menos de juguetería. En la consulta deberán aparecer los campos “Sección” y “Media por sección”.
"""
pd.read_sql("SELECT SECCIÓN, AVG(PRECIO), SUM(PRECIO) FROM productos WHERE SECCIÓN != 'JUGUETERÍA' GROUP BY SECCIÓN",engine)

      SECCIÓN   AVG(PRECIO)  SUM(PRECIO)
0  FERRETERÍA     13.625800      95.3806
1  CONFECCIÓN  55727.143722  501544.2935
2    DEPORTES    130.581230    1305.8123
3    CERÁMICA     73.724967     442.3498
4     OFICINA     39.760600      39.7606

In [29]:
"""
5.	Realizar Una consulta que muestre cuantos artículos hay de la sección “Deportes”.
"""
pd.read_sql("SELECT SECCIÓN, COUNT(CÓDIGOARTÍCULO) FROM productos WHERE SECCIÓN = 'DEPORTES' GROUP BY SECCIÓN",engine)

    SECCIÓN  COUNT(CÓDIGOARTÍCULO)
0  DEPORTES                     10

### Consultas de calculo
Cada gestor de base de datos tiene las suyas propias
- Now(): Dia y hora actuales
- Datediff(): Diferencia que hay entre dos fechas
- Date_format(): Para quitar decimales y redondear
- Round():
- Truncate():
- Concat():

In [30]:
pd.read_sql("SELECT NOMBREARTÍCULO, SECCIÓN, PRECIO, ROUND(PRECIO+(PRECIO*0.21),2) AS PRECIO_IVA FROM productos",engine)

         NOMBREARTÍCULO     SECCIÓN       PRECIO  PRECIO_IVA
0        DESTORNILLADOR  FERRETERÍA       6.6280        8.02
1       TRAJE CABALLERO  CONFECCIÓN     284.5769      344.34
2    COCHE TELEDIRIGIDO  JUGUETERÍA     159.4462      192.93
3         RAQUETA TENIS    DEPORTES      93.4694      113.10
4            MANCUERNAS    DEPORTES      60.0000       72.60
5              SERRUCHO  CONFECCIÓN      30.2045       36.55
6         CORREPASILLOS  JUGUETERÍA     103.3356      125.04
7       PANTALÓN SEÑORA  CONFECCIÓN     174.2310      210.82
8         CONSOLA VIDEO  JUGUETERÍA     442.5444      535.48
9                 TUBOS    CERÁMICA     168.4253      203.79
10        LLAVE INGLESA  FERRETERÍA      24.3986       29.52
11     CAMISA CABALLERO  CONFECCIÓN      67.1306       81.23
12       TREN ELÉCTRICO  JUGUETERÍA    1505.3766     1821.51
13     PLATO DECORATIVO    CERÁMICA      54.0911       65.45
14             ALICATES  FERRETERÍA       6.7362        8.15
15      MUÑECA ANDADORA  JUGUETERÍA     105.0593      127.12
16     PISTOLA OLÍMPICA    DEPORTES      46.7347       56.55
17           BLUSA SRA.  CONFECCIÓN     101.0566      122.28
18          JUEGO DE TE    CERÁMICA      43.2728       52.36
19             CENICERO    CERÁMICA      19.7468       23.89
20             MARTILLO  FERRETERÍA      11.3952       13.79
21        CAZADORA PIEL  CONFECCIÓN     522.6930      632.46
22          BALÓN RUGBY    DEPORTES     111.6440      135.09
23     BALÓN BALONCESTO    DEPORTES      75.2731       91.08
24   FUERTE DE SOLDADOS  JUGUETERÍA     143.7020      173.88
25     ABRIGO CABALLERO  CONFECCIÓN  500000.0000   605000.00
26         BALÓN FÚTBOL    DEPORTES      43.9147       53.14
27           ABRIGO SRA  CONFECCIÓN     360.0736      435.69
28       DESTORNILLADOR  FERRETERÍA       9.0584       10.96
29  PISTOLA CON SONIDOS  JUGUETERÍA      57.2500       69.27
30           CRONÓMETRO    DEPORTES     439.1764      531.40
31               MACETA    CERÁMICA      29.0434       35.14
32       PIE DE LÁMPARA     OFICINA      39.7606       48.11
33          LIMA GRANDE  FERRETERÍA      22.0692       26.70
34      JUEGO DE BROCAS  FERRETERÍA      15.0950       18.26
35     CINTURÓN DE PIEL  CONFECCIÓN       4.3273        5.24
36        CAÑA DE PESCA    DEPORTES     270.0000      326.70
37          JARRA CHINA    CERÁMICA     127.7704      154.60
38       BOTA ALPINISMO    DEPORTES     144.0000      174.24
39   PALAS DE PING PONG    DEPORTES      21.6000       26.14

In [31]:
"""
1. Realizar una consulta que visualice los campos NOMBRE ARTÍCULO,
SECCIÓN, PRECIO de la tabla PRODUCTOS y un campo nuevo que
nombramos con el texto “DESCUENTO_7”. Debe mostrar el resultado de aplicar
sobre el campo PRECIO un descuento de un 7 %. El formato del nuevo campo
para debe aparecer con 2 lugares decimales. 
"""
pd.read_sql("SELECT NOMBREARTÍCULO, SECCIÓN, PRECIO, ROUND(PRECIO-(PRECIO*0.07),2) AS DESCUENTO_7 FROM productos ",engine)

         NOMBREARTÍCULO     SECCIÓN       PRECIO  DESCUENTO_7
0        DESTORNILLADOR  FERRETERÍA       6.6280         6.16
1       TRAJE CABALLERO  CONFECCIÓN     284.5769       264.66
2    COCHE TELEDIRIGIDO  JUGUETERÍA     159.4462       148.28
3         RAQUETA TENIS    DEPORTES      93.4694        86.93
4            MANCUERNAS    DEPORTES      60.0000        55.80
5              SERRUCHO  CONFECCIÓN      30.2045        28.09
6         CORREPASILLOS  JUGUETERÍA     103.3356        96.10
7       PANTALÓN SEÑORA  CONFECCIÓN     174.2310       162.03
8         CONSOLA VIDEO  JUGUETERÍA     442.5444       411.57
9                 TUBOS    CERÁMICA     168.4253       156.64
10        LLAVE INGLESA  FERRETERÍA      24.3986        22.69
11     CAMISA CABALLERO  CONFECCIÓN      67.1306        62.43
12       TREN ELÉCTRICO  JUGUETERÍA    1505.3766      1400.00
13     PLATO DECORATIVO    CERÁMICA      54.0911        50.30
14             ALICATES  FERRETERÍA       6.7362         6.26
15      MUÑECA ANDADORA  JUGUETERÍA     105.0593        97.71
16     PISTOLA OLÍMPICA    DEPORTES      46.7347        43.46
17           BLUSA SRA.  CONFECCIÓN     101.0566        93.98
18          JUEGO DE TE    CERÁMICA      43.2728        40.24
19             CENICERO    CERÁMICA      19.7468        18.36
20             MARTILLO  FERRETERÍA      11.3952        10.60
21        CAZADORA PIEL  CONFECCIÓN     522.6930       486.10
22          BALÓN RUGBY    DEPORTES     111.6440       103.83
23     BALÓN BALONCESTO    DEPORTES      75.2731        70.00
24   FUERTE DE SOLDADOS  JUGUETERÍA     143.7020       133.64
25     ABRIGO CABALLERO  CONFECCIÓN  500000.0000    465000.00
26         BALÓN FÚTBOL    DEPORTES      43.9147        40.84
27           ABRIGO SRA  CONFECCIÓN     360.0736       334.87
28       DESTORNILLADOR  FERRETERÍA       9.0584         8.42
29  PISTOLA CON SONIDOS  JUGUETERÍA      57.2500        53.24
30           CRONÓMETRO    DEPORTES     439.1764       408.43
31               MACETA    CERÁMICA      29.0434        27.01
32       PIE DE LÁMPARA     OFICINA      39.7606        36.98
33          LIMA GRANDE  FERRETERÍA      22.0692        20.52
34      JUEGO DE BROCAS  FERRETERÍA      15.0950        14.04
35     CINTURÓN DE PIEL  CONFECCIÓN       4.3273         4.02
36        CAÑA DE PESCA    DEPORTES     270.0000       251.10
37          JARRA CHINA    CERÁMICA     127.7704       118.83
38       BOTA ALPINISMO    DEPORTES     144.0000       133.92
39   PALAS DE PING PONG    DEPORTES      21.6000        20.09

In [32]:
# Utilizando funciones NOW() y DATEDIFF()
pd.read_sql("SELECT FECHA, NOW(), DATEDIFF(NOW(),FECHA) AS DIAS_DIFERENCIA FROM productos",engine)

        FECHA               NOW()  DIAS_DIFERENCIA
0  2000-10-22 2026-03-14 13:53:39             9274
1  2002-03-11 2026-03-14 13:53:39             8769
2  2002-05-26 2026-03-14 13:53:39             8693
3  2000-03-20 2026-03-14 13:53:39             9490
4  2000-09-13 2026-03-14 13:53:39             9313
5  2001-03-23 2026-03-14 13:53:39             9122
6  2000-04-11 2026-03-14 13:53:39             9468
7  2000-01-10 2026-03-14 13:53:39             9560
8  2002-09-24 2026-03-14 13:53:39             8572
9  2000-02-04 2026-03-14 13:53:39             9535
10 2001-05-23 2026-03-14 13:53:39             9061
11 2002-08-11 2026-03-14 13:53:39             8616
12 2001-07-03 2026-03-14 13:53:39             9020
13 2000-06-07 2026-03-14 13:53:39             9411
14 2000-04-17 2026-03-14 13:53:39             9462
15 2001-01-04 2026-03-14 13:53:39             9200
16 2001-02-02 2026-03-14 13:53:39             9171
17 2000-03-18 2026-03-14 13:53:39             9492
18 2001-01-15 2026-03-14 13:53:39             9189
19 2001-07-02 2026-03-14 13:53:39             9021
20 2001-09-04 2026-03-14 13:53:39             8957
21 2001-07-10 2026-03-14 13:53:39             9013
22 2000-11-11 2026-03-14 13:53:39             9254
23 2001-06-25 2026-03-14 13:53:39             9028
24 2000-11-25 2026-03-14 13:53:39             9240
25 2002-04-05 2026-03-14 13:53:39             8744
26 2002-07-04 2026-03-14 13:53:39             8654
27 2001-05-03 2026-03-14 13:53:39             9081
28 2002-02-20 2026-03-14 13:53:39             8788
29 2001-04-15 2026-03-14 13:53:39             9099
30 2002-01-03 2026-03-14 13:53:39             8836
31 2000-02-23 2026-03-14 13:53:39             9516
32 2001-05-27 2026-03-14 13:53:39             9057
33 2002-08-10 2026-03-14 13:53:39             8617
34 2002-07-04 2026-03-14 13:53:39             8654
35 2002-05-12 2026-03-14 13:53:39             8707
36 2000-02-14 2026-03-14 13:53:39             9525
37 2002-09-02 2026-03-14 13:53:39             8594
38 2002-05-05 2026-03-14 13:53:39             8714
39 2002-02-02 2026-03-14 13:53:39             8806

In [33]:
"""
2.Realizar una consulta visualizando los campos FECHA, SECCIÓN, NOMBRE
ARTÍCULO y PRECIO de la tabla PRODUCTOS y un campo nuevo que
nombramos con el texto “DTO2 €_EN_CERÁMICA”. Debe mostrar el resultado
de aplicar sobre el campo PRECIO la resta de 2 € sólo a los artículos de la sección
CERÁMICA. El formato del nuevo campo debe aparecer con 2 lugares decimales.
Ordenar el resultado de la consulta por el campo FECHA descendente. 
"""
pd.read_sql("SELECT FECHA, SECCIÓN, NOMBREARTÍCULO, PRECIO, PRECIO-2 AS DTO2e_EN_CERAMICA FROM productos",engine)

        FECHA     SECCIÓN       NOMBREARTÍCULO       PRECIO  DTO2e_EN_CERAMICA
0  2000-10-22  FERRETERÍA       DESTORNILLADOR       6.6280             4.6280
1  2002-03-11  CONFECCIÓN      TRAJE CABALLERO     284.5769           282.5769
2  2002-05-26  JUGUETERÍA   COCHE TELEDIRIGIDO     159.4462           157.4462
3  2000-03-20    DEPORTES        RAQUETA TENIS      93.4694            91.4694
4  2000-09-13    DEPORTES           MANCUERNAS      60.0000            58.0000
5  2001-03-23  CONFECCIÓN             SERRUCHO      30.2045            28.2045
6  2000-04-11  JUGUETERÍA        CORREPASILLOS     103.3356           101.3356
7  2000-01-10  CONFECCIÓN      PANTALÓN SEÑORA     174.2310           172.2310
8  2002-09-24  JUGUETERÍA        CONSOLA VIDEO     442.5444           440.5444
9  2000-02-04    CERÁMICA                TUBOS     168.4253           166.4253
10 2001-05-23  FERRETERÍA        LLAVE INGLESA      24.3986            22.3986
11 2002-08-11  CONFECCIÓN     CAMISA CABALLERO      67.1306            65.1306
12 2001-07-03  JUGUETERÍA       TREN ELÉCTRICO    1505.3766          1503.3766
13 2000-06-07    CERÁMICA     PLATO DECORATIVO      54.0911            52.0911
14 2000-04-17  FERRETERÍA             ALICATES       6.7362             4.7362
15 2001-01-04  JUGUETERÍA      MUÑECA ANDADORA     105.0593           103.0593
16 2001-02-02    DEPORTES     PISTOLA OLÍMPICA      46.7347            44.7347
17 2000-03-18  CONFECCIÓN           BLUSA SRA.     101.0566            99.0566
18 2001-01-15    CERÁMICA          JUEGO DE TE      43.2728            41.2728
19 2001-07-02    CERÁMICA             CENICERO      19.7468            17.7468
20 2001-09-04  FERRETERÍA             MARTILLO      11.3952             9.3952
21 2001-07-10  CONFECCIÓN        CAZADORA PIEL     522.6930           520.6930
22 2000-11-11    DEPORTES          BALÓN RUGBY     111.6440           109.6440
23 2001-06-25    DEPORTES     BALÓN BALONCESTO      75.2731            73.2731
24 2000-11-25  JUGUETERÍA   FUERTE DE SOLDADOS     143.7020           141.7020
25 2002-04-05  CONFECCIÓN     ABRIGO CABALLERO  500000.0000        499998.0000
26 2002-07-04    DEPORTES         BALÓN FÚTBOL      43.9147            41.9147
27 2001-05-03  CONFECCIÓN           ABRIGO SRA     360.0736           358.0736
28 2002-02-20  FERRETERÍA       DESTORNILLADOR       9.0584             7.0584
29 2001-04-15  JUGUETERÍA  PISTOLA CON SONIDOS      57.2500            55.2500
30 2002-01-03    DEPORTES           CRONÓMETRO     439.1764           437.1764
31 2000-02-23    CERÁMICA               MACETA      29.0434            27.0434
32 2001-05-27     OFICINA       PIE DE LÁMPARA      39.7606            37.7606
33 2002-08-10  FERRETERÍA          LIMA GRANDE      22.0692            20.0692
34 2002-07-04  FERRETERÍA      JUEGO DE BROCAS      15.0950            13.0950
35 2002-05-12  CONFECCIÓN     CINTURÓN DE PIEL       4.3273             2.3273
36 2000-02-14    DEPORTES        CAÑA DE PESCA     270.0000           268.0000
37 2002-09-02    CERÁMICA          JARRA CHINA     127.7704           125.7704
38 2002-05-05    DEPORTES       BOTA ALPINISMO     144.0000           142.0000
39 2002-02-02    DEPORTES   PALAS DE PING PONG      21.6000            19.6000

In [34]:
""" 
Realizar una consulta visualizando los campos FECHA, SECCIÓN, NOMBRE
ARTÍCULO y PRECIO de la tabla PRODUCTOS y un campo nuevo que
nombramos con el texto “DTO2 €_EN_CERÁMICA”. Debe mostrar el resultado
de aplicar sobre el campo PRECIO la resta de 2 € sólo a los artículos de la sección
CERÁMICA. El formato del nuevo campo debe aparecer con 2 lugares decimales.
Ordenar el resultado de la consulta por el campo FECHA descendente. 
"""
pd.read_sql("SELECT FECHA, SECCIÓN, NOMBREARTÍCULO, PRECIO, ROUND(PRECIO-2,2) AS DTO2e_EN_CERAMICA FROM productos WHERE SECCIÓN = 'CERAMICA' ORDER BY FECHA DESC",engine)

       FECHA   SECCIÓN    NOMBREARTÍCULO    PRECIO  DTO2e_EN_CERAMICA
0 2002-09-02  CERÁMICA       JARRA CHINA  127.7704             125.77
1 2001-07-02  CERÁMICA          CENICERO   19.7468              17.75
2 2001-01-15  CERÁMICA       JUEGO DE TE   43.2728              41.27
3 2000-06-07  CERÁMICA  PLATO DECORATIVO   54.0911              52.09
4 2000-02-23  CERÁMICA            MACETA   29.0434              27.04
5 2000-02-04  CERÁMICA             TUBOS  168.4253             166.43

In [35]:
""" 
Realizar una consulta visualizando los campos NOMBRE ARTÍCULO, SECCIÓN, PRECIO de la tabla PRODUCTOS y
un campo nuevo que nombramos con el texto “PRECIO_AUMENTADO_EN_2”. 
Debe mostrar el PRECIO con un incremento de un 2% del PRECIO. 
Sólo debemos tener en cuenta los registros de la sección FERRETERÍA. 
El nuevo campo debe aparecer en Euros y con 2 lugares decimales.
"""
pd.read_sql("SELECT NOMBREARTÍCULO, SECCIÓN, PRECIO, ROUND(PRECIO*1.02,2) AS PRECIO_AUMENTADO_EN_2  FROM productos WHERE SECCIÓN = 'FERRETERÍA'", engine)

    NOMBREARTÍCULO     SECCIÓN   PRECIO  PRECIO_AUMENTADO_EN_2
0   DESTORNILLADOR  FERRETERÍA   6.6280                   6.76
1    LLAVE INGLESA  FERRETERÍA  24.3986                  24.89
2         ALICATES  FERRETERÍA   6.7362                   6.87
3         MARTILLO  FERRETERÍA  11.3952                  11.62
4   DESTORNILLADOR  FERRETERÍA   9.0584                   9.24
5      LIMA GRANDE  FERRETERÍA  22.0692                  22.51
6  JUEGO DE BROCAS  FERRETERÍA  15.0950                  15.40

In [36]:
"""
Realiza una consulta que muestre los campos:

NOMBREARTÍCULO

SECCIÓN

PRECIO

y un campo nuevo llamado PRECIO_DESCUENTO_EN_5.

✅ El campo nuevo debe mostrar el PRECIO con un descuento del 5%.
✅ Solo considerar los registros de la sección JUGUETERÍA.
✅ El nuevo campo debe mostrarse en euros y con 2 decimales.
"""

pd.read_sql("SELECT NOMBREARTÍCULO, SECCIÓN, PRECIO, ROUND(PRECIO-(PRECIO*0.05),2) AS PRECIO_DESCUENTO_EN_5 FROM productos WHERE SECCIÓN = 'JUGUETERÍA'",engine)

        NOMBREARTÍCULO     SECCIÓN     PRECIO  PRECIO_DESCUENTO_EN_5
0   COCHE TELEDIRIGIDO  JUGUETERÍA   159.4462                 151.47
1        CORREPASILLOS  JUGUETERÍA   103.3356                  98.17
2        CONSOLA VIDEO  JUGUETERÍA   442.5444                 420.42
3       TREN ELÉCTRICO  JUGUETERÍA  1505.3766                1430.11
4      MUÑECA ANDADORA  JUGUETERÍA   105.0593                  99.81
5   FUERTE DE SOLDADOS  JUGUETERÍA   143.7020                 136.52
6  PISTOLA CON SONIDOS  JUGUETERÍA    57.2500                  54.39

### Consultas Multitabla
#### Union externa
- UNION: (Hay restricciones) Unir dos tablas pero se requiere que estas dos tengan el mismo numero de columnas (variables) y tambien el tipo de las variables (cuantitativa o cualitativa) debe ser semejante, el nombre no importa
- UNION ALL: En UNION puede haber registros repetidos asi que solo muestra ese registro solo una vez, con UNION ALL se muestran todos los registros repetidos

Tambien se pueden unir mas de dos tablas

In [37]:
pd.read_sql("DESCRIBE ProductosNuevos",engine)

            Field        Type Null Key Default Extra
0  CÓDIGOARTÍCULO        text  YES        None
1         SECCIÓN        text  YES        None
2  NOMBREARTÍCULO        text  YES        None
3          PRECIO      double  YES        None
4           FECHA    datetime  YES        None
5       IMPORTADO  tinyint(1)  YES        None
6    PAÍSDEORIGEN        text  YES        None
7            FOTO      double  YES        None

In [38]:
pd.read_sql("SELECT * FROM ProductosNuevos",engine)

,CÓDIGOARTÍCULO,SECCIÓN,NOMBREARTÍCULO,PRECIO,FECHA,IMPORTADO,PAÍSDEORIGEN,FOTO
0,AR50,ALTA COSTURA,TRAJE CABALLERO,1284.5769,2002-03-11,0,ITALIA,None
1,AR51,DEPORTES DE RIESGO,RAQUETA TENIS,1093.4694,2000-03-20,0,USA,None
2,AR52,DEPORTES DE RIESGO,MANCUERNAS,1060.0000,2000-09-13,0,USA,None
3,AR53,ALTA COSTURA,SERRUCHO,1030.2045,2001-03-23,0,FRANCIA,None
4,AR54,ALTA COSTURA,PANTALÓN SEÑORA,1174.2310,2000-01-10,0,MARRUECOS,None
5,AR55,ALTA COSTURA,CAMISA CABALLERO,1067.1306,2002-08-11,0,ESPAÑA,None
6,AR56,DEPORTES DE RIESGO,PISTOLA OLÍMPICA,1046.7347,2001-02-02,0,SUECIA,None
7,AR57,ALTA COSTURA,BLUSA SRA.,1101.0566,2000-03-18,0,CHINA,None
8,AR58,ALTA COSTURA,CAZADORA PIEL,1522.6930,2001-07-10,0,ITALIA,None
9,AR59,DEPORTES DE RIESGO,BALÓN RUGBY,1111.6440,2000-11-11,0,USA,None
10,AR60,DEPORTES DE RIESGO,BALÓN BALONCESTO,1075.2731,2001-06-25,0,JAPÓN,None
11,AR61,ALTA COSTURA,ABRIGO CABALLERO,1500.0000,2002-04-05,0,ITALIA,None
12,AR62,DEPORTES DE RIESGO,BALÓN FÚTBOL,1043.9147,2002-07-04,0,ESPAÑA,None
13,AR63,ALTA COSTURA,ABRIGO SRA,1360.0736,2001-05-03,0,MARRUECOS,None
14,AR64,DEPORTES DE RIESGO,CRONÓMETRO,1439.1764,2002-01-03,0,USA,None
15,AR65,ALTA COSTURA,CINTURÓN DE PIEL,1004.3273,2002-05-12,0,ESPAÑA,None
16,AR66,DEPORTES DE RIESGO,CAÑA DE PESCA,1270.0000,2000-02-14,0,USA,None
17,AR67,DEPORTES DE RIESGO,BOTA ALPINISMO,1144.0000,2002-05-05,0,ESPAÑA,None
18,AR68,DEPORTES DE RIESGO,PALAS DE PING PONG,1021.6000,2002-02-02,0,ESPAÑA,None

In [39]:
# Ambas consultas select deben tener indicados los mismos campos (en numero, pueden ser campos diferentes pero 3 campos
# a la izq como a la derecha)
pd.read_sql("SELECT * FROM productos WHERE SECCIÓN = 'DEPORTES' UNION SELECT * FROM ProductosNuevos WHERE SECCIÓN = 'DEPORTES DE RIESGO'", engine)

,CÓDIGOARTÍCULO,SECCIÓN,NOMBREARTÍCULO,PRECIO,FECHA,IMPORTADO,PAÍSDEORIGEN,FOTO
0,AR04,DEPORTES,RAQUETA TENIS,93.4694,2000-03-20,0,USA,None
1,AR06,DEPORTES,MANCUERNAS,60.0000,2000-09-13,0,USA,None
2,AR18,DEPORTES,PISTOLA OLÍMPICA,46.7347,2001-02-02,0,SUECIA,None
3,AR24,DEPORTES,BALÓN RUGBY,111.6440,2000-11-11,0,USA,None
4,AR25,DEPORTES,BALÓN BALONCESTO,75.2731,2001-06-25,0,JAPÓN,None
5,AR28,DEPORTES,BALÓN FÚTBOL,43.9147,2002-07-04,0,ESPAÑA,None
6,AR32,DEPORTES,CRONÓMETRO,439.1764,2002-01-03,0,USA,None
7,AR38,DEPORTES,CAÑA DE PESCA,270.0000,2000-02-14,0,USA,None
8,AR40,DEPORTES,BOTA ALPINISMO,144.0000,2002-05-05,0,ESPAÑA,None
9,AR41,DEPORTES,PALAS DE PING PONG,21.6000,2002-02-02,0,ESPAÑA,None
10,AR51,DEPORTES DE RIESGO,RAQUETA TENIS,1093.4694,2000-03-20,0,USA,None
11,AR52,DEPORTES DE RIESGO,MANCUERNAS,1060.0000,2000-09-13,0,USA,None
12,AR56,DEPORTES DE RIESGO,PISTOLA OLÍMPICA,1046.7347,2001-02-02,0,SUECIA,None
13,AR59,DEPORTES DE RIESGO,BALÓN RUGBY,1111.6440,2000-11-11,0,USA,None
14,AR60,DEPORTES DE RIESGO,BALÓN BALONCESTO,1075.2731,2001-06-25,0,JAPÓN,None
15,AR62,DEPORTES DE RIESGO,BALÓN FÚTBOL,1043.9147,2002-07-04,0,ESPAÑA,None
16,AR64,DEPORTES DE RIESGO,CRONÓMETRO,1439.1764,2002-01-03,0,USA,None
17,AR66,DEPORTES DE RIESGO,CAÑA DE PESCA,1270.0000,2000-02-14,0,USA,None
18,AR67,DEPORTES DE RIESGO,BOTA ALPINISMO,1144.0000,2002-05-05,0,ESPAÑA,None
19,AR68,DEPORTES DE RIESGO,PALAS DE PING PONG,1021.6000,2002-02-02,0,ESPAÑA,None

In [40]:
pd.read_sql("SELECT * FROM productos WHERE PRECIO >500 UNION SELECT * FROM ProductosNuevos WHERE SECCIÓN ='ALTA COSTURA' ORDER BY SECCIÓN", engine)

,CÓDIGOARTÍCULO,SECCIÓN,NOMBREARTÍCULO,PRECIO,FECHA,IMPORTADO,PAÍSDEORIGEN,FOTO
0,AR50,ALTA COSTURA,TRAJE CABALLERO,1284.5769,2002-03-11,0,ITALIA,None
1,AR53,ALTA COSTURA,SERRUCHO,1030.2045,2001-03-23,0,FRANCIA,None
2,AR54,ALTA COSTURA,PANTALÓN SEÑORA,1174.2310,2000-01-10,0,MARRUECOS,None
3,AR55,ALTA COSTURA,CAMISA CABALLERO,1067.1306,2002-08-11,0,ESPAÑA,None
4,AR57,ALTA COSTURA,BLUSA SRA.,1101.0566,2000-03-18,0,CHINA,None
5,AR58,ALTA COSTURA,CAZADORA PIEL,1522.6930,2001-07-10,0,ITALIA,None
6,AR61,ALTA COSTURA,ABRIGO CABALLERO,1500.0000,2002-04-05,0,ITALIA,None
7,AR63,ALTA COSTURA,ABRIGO SRA,1360.0736,2001-05-03,0,MARRUECOS,None
8,AR65,ALTA COSTURA,CINTURÓN DE PIEL,1004.3273,2002-05-12,0,ESPAÑA,None
9,AR23,CONFECCIÓN,CAZADORA PIEL,522.6930,2001-07-10,0,ITALIA,None
10,AR27,CONFECCIÓN,ABRIGO CABALLERO,500000.0000,2002-04-05,0,ITALIA,None
11,AR14,JUGUETERÍA,TREN ELÉCTRICO,1505.3766,2001-07-03,0,JAPÓN,None

#### Union interna
- INNER JOIN
- LEFT JOIN 
- RIGHT JOIN

In [41]:
pd.read_sql("SELECT * FROM clientes_access",engine)

,CÓDIGOCLIENTE,EMPRESA,DIRECCIÓN,POBLACIÓN,TELÉFONO,RESPONSABLE,HISTORIAL
0,CT01,BELTRÁN E HIJOS,LAS FUENTES 78,MADRID,914456435,ANGEL MARTÍNEZ,None
1,CT02,LA MODERNA,LA PALOMA 123,OVIEDO,985323434,JUAN GARCÍA,None
2,CT03,EL ESPAÑOLITO,MOTORES 34,BARCELONA,934565343,ANA FERNÁNDEZ,None
3,CT04,EXPORTASA,VALLECAS 34,MADRID,913452378,ELVIRA GÓMEZ,None
4,CT06,CONFECCIONES AMPARO,LOS MOROS 23,GIJÓN,985754332,LUÍS ÁLVAREZ,None
5,CT07,LA CASA DEL JUGUETE,AMÉRICA 45,MADRID,912649987,ELÍAS PÉREZ,None
6,CT08,JUGUETERÍA SUÁREZ,PARIS 123,BARCELONA,933457866,JUAN GARCÍA,None
7,CT09,ALMACÉN POPULAR,LAS FUENTES 124,BILBAO,942347127,JOSÉ ÁLVAREZ,None
8,CT10,FERETERÍA EL CLAVO,PASEO DE ÁLAMOS 78,MADRID,914354866,MANUEL MENÉNDEZ,None
9,CT11,JUGUETES MARTÍNEZ,VIA LAYETANA 245,BARCELONA,936628554,FRANCISCO CUEVAS,None
10,CT12,FERNÁNDEZ SL,PASEO DEL MAR 45,SANTANDER,942049586,ELISA COLLADO,None
11,CT13,CONFECCIONES ARTÍMEZ,GENERAL PERÓN 45,A CORUÑA,981345239,ESTEBAN PASCUAL,None
12,CT14,DEPORTES GARCÍA,GUZMÁN EL BUENO 45,MADRID,913299475,ANA JIMÉNEZ,None
13,CT15,EXCLUSIVAS FERNÁNDEZ,LLOBREGAT 250,BARCELONA,939558365,LUISA FERNÁNDEZ,None
14,CT16,DEPORTES MORÁN,AUTONOMÍA 45,LUGO,982986944,JOSÉ MANZANO,None
15,CT17,BAZAR FRANCISCO,CARMEN 45,ZAMORA,980495288,CARLOS BELTRÁN,None
16,CT18,JUGUETES LA SONRISA,LA BAÑEZA 67,LEÓN,987945368,FAUSTINO PÉREZ,None
17,CT19,CONFECCIONES GALÁN,FUENCARRAL 78,MADRID,913859234,JUAN GARCÍA,None
18,CT20,LA CURTIDORA,OLIVARES 3,MÁLAGA,953756259,MARÍA GÓMEZ,None
19,CT21,LÍNEA JOVEN,SIERPES 78,SEVILLA,953452567,ASUNCIÓN SALADO,None
20,CT22,BAZAR EL BARAT,DIAGONAL 56,BARCELONA,936692866,ELISA DAPENA,None
21,CT23,EL PALACIO DE LA MODA,ORTEGA Y GASSET 129,MADRID,927785235,LAURA CARRASCO,None
22,CT24,SÁEZ Y CÍA,INFANTA MERCEDS 23,SEVILLA,954869234,MANUEL GUERRA,None
23,CT25,DEPORTES EL MADRILEÑO,CASTILLA 345,ZARAGOZA,976388934,CARLOS GONZÁLEZ,None
24,CT26,FERRETERÍA LA ESCOBA,ORENSE 7,MADRID,918459346,JOSÉ GARCÍA,None
25,CT27,JUGUETES EL BARATO,VÍA AUGUSTA 245,BARCELONA,933486984,ELVIRA IGLESIAS,None
26,CT28,CONFECCIONES HERMINIA,CORRIDA 345,GIJÓN,985597315,ABEL GONZÁLEZ,None
27,CT30,BAZAR EL ARGENTINO,ATOCHA 55,MADRID,912495973,ADRIÁN ÁLVAREZ,None
28,CT31,LA TIENDA ELEGANTE,EL COMENDADOR 67,ZARAGOZA,975694035,JOSÉ PASCUAL,None
29,CT32,DEPORTES NAUTICOS GARCÍA,JUAN FERNÁNDEZ 89,ÁVILA,920268648,JUAN CONRADO,None
30,CT33,CONFECCIONES RUIZ,LLOBREGAT 345,BARCELONA,934587615,CARLOS SANZ,None
31,CT34,BAZAR LA FARAONA,CASTILLA Y LEÓN 34,MADRID,915483627,ANGEL SANTAMARÍA,None
32,CT35,FERRETERÍA EL MARTILLO,CASTELLANOS 205,SALAMANCA,923548965,JOAQUÍN FERNANDEZ,None
33,CT36,JUGUETES EDUCATIVOS SANZ,ORENSE 89,MADRID,916872354,PEDRO IGLESIAS,None
34,CT37,ALMACENES FERNANDEZ,ANTÓN 67,TERUEL,978564025,MARIA ARDANZA,None
35,CT38,CONFECCIONES MÓNICA,MOTORES 67,BARCELONA,935681245,PEDRO SERRANO,None
36,CT39,FERRETERÍA LIMA,VALLECAS 45,MADRID,913532785,LUIS GARCÍA,None
37,CT40,DEPORTES EL BRASILEÑO,ABEL MARTÍNEZ 67,SALAMANCA,921548762,CARLOS GÓMEZ,None

In [42]:
pd.read_sql("SELECT * FROM pedidos_access",engine)

,NÚMERO DE PEDIDO,CÓDIGO CLIENTE,FECHA DE PEDIDO,FORMA DE PAGO,DESCUENTO,ENVIADO
0,1,CT01,2000-03-11 00:00:00,CONTADO,0.02,1
1,3,CT23,2000-03-18 00:00:00,APLAZADO,0.06,0
2,5,CT25,2000-03-31 00:00:00,CONTADO,0.09,0
3,7,CT12,2000-04-12 00:00:00,CONTADO,0.07,0
4,8,CT01,2000-04-15 00:00:00,TARJETA,0.02,1
5,9,CT21,2000-04-21 00:00:00,CONTADO,0.04,0
6,11,CT04,2001-05-01 00:00:00,CONTADO,0.08,1
7,12,CT06,2001-05-19 00:00:00,CONTADO,0.09,1
8,13,CT13,2000-04-30 00:00:00,APLAZADO,0.03,0
9,16,CT25,2001-05-11 00:00:00,CONTADO,0.12,0
10,19,CT10,2002-05-22 00:00:00,CONTADO,0.07,1
11,21,CT16,2001-05-28 00:00:00,CONTADO,0.03,0
12,22,CT07,2000-05-31 00:00:00,TARJETA,0.05,1
13,25,CT18,2000-06-02 00:00:00,CONTADO,0.06,0
14,26,CT09,2001-06-04 00:00:00,APLAZADO,0.07,1
15,27,CT34,2000-06-06 00:00:00,CONTADO,0.04,0
16,28,CT28,2000-06-08 00:00:00,APLAZADO,0.08,0
17,29,CT30,2001-04-02 00:00:00,TARJETA,0.06,0
18,30,CT02,2000-08-15 00:00:00,CONTADO,0.06,1
19,31,CT30,2000-06-08 00:00:00,TARJETA,0.05,1
20,32,CT14,2001-06-20 00:00:00,APLAZADO,0.06,0
21,34,CT26,2002-06-23 00:00:00,TARJETA,0.05,0
22,35,CT26,2001-06-30 00:00:00,CONTADO,0.06,0
23,37,CT24,2001-07-02 00:00:00,TARJETA,0.03,1
24,39,CT20,2001-07-08 00:00:00,TARJETA,0.06,1
25,40,CT04,2002-07-12 00:00:00,CONTADO,0.12,0
26,42,CT34,2002-07-15 00:00:00,APLAZADO,0.07,1
27,43,CT09,2001-07-18 00:00:00,CONTADO,0.07,0
28,44,CT34,2002-07-20 00:00:00,APLAZADO,0.04,0
29,45,CT30,2002-07-22 00:00:00,TARJETA,0.07,0
30,46,CT31,2002-07-25 00:00:00,CONTADO,0.06,0
31,47,CT34,2000-07-31 00:00:00,APLAZADO,0.08,0
32,48,CT18,2002-08-30 00:00:00,CONTADO,0.03,0
33,49,CT28,2002-09-02 00:00:00,CONTADO,0.03,0
34,50,CT09,2002-09-05 00:00:00,APLAZADO,0.08,0
35,51,CT09,2002-09-05 00:00:00,CONTADO,0.05,1
36,63,CT28,2000-09-10 00:00:00,CONTADO,0.09,0
37,72,CT01,2002-08-18 00:00:00,CONTADO,0.05,1
38,73,CT01,2001-08-02 00:00:00,CONTADO,0.07,0
39,74,CT01,2002-09-17 00:00:00,APLAZADO,0.08,0
40,75,CT01,2002-09-30 00:00:00,TARJETA,0.12,0
41,76,CT01,2002-10-19 00:00:00,CONTADO,0.04,1
42,77,CT01,2000-10-28 00:00:00,CONTADO,0.05,0
43,79,CT34,2000-12-12 00:00:00,CONTADO,0.05,0
44,85,CT04,2002-12-23 00:00:00,TARJETA,0.04,0
45,86,CT09,2001-12-24 00:00:00,APLAZADO,0.03,0
46,98,CT01,2001-12-27 00:00:00,CONTADO,0.08,1
47,102,CT06,2001-01-12 00:00:00,CONTADO,0.07,1
48,103,CT02,2001-01-24 00:00:00,CONTADO,0.04,0
49,105,CT30,2001-01-01 00:00:00,APLAZADO,0.09,0
50,5005,CT30,2002-08-10 00:00:00,TARJETA,0.00,1
51,5050,CT30,2002-03-27 00:00:00,TARJETA,0.00,1

In [43]:
pd.read_sql("SELECT * FROM clientes_access c INNER JOIN pedidos_access p ON c.`CÓDIGOCLIENTE`=p.`CÓDIGO CLIENTE` WHERE POBLACIÓN = 'MADRID' ORDER BY CÓDIGOCLIENTE",engine)

,CÓDIGOCLIENTE,EMPRESA,DIRECCIÓN,POBLACIÓN,TELÉFONO,RESPONSABLE,HISTORIAL,NÚMERO DE PEDIDO,CÓDIGO CLIENTE,FECHA DE PEDIDO,FORMA DE PAGO,DESCUENTO,ENVIADO
0,CT01,BELTRÁN E HIJOS,LAS FUENTES 78,MADRID,914456435,ANGEL MARTÍNEZ,None,75,CT01,2002-09-30 00:00:00,TARJETA,0.12,0
1,CT01,BELTRÁN E HIJOS,LAS FUENTES 78,MADRID,914456435,ANGEL MARTÍNEZ,None,8,CT01,2000-04-15 00:00:00,TARJETA,0.02,1
2,CT01,BELTRÁN E HIJOS,LAS FUENTES 78,MADRID,914456435,ANGEL MARTÍNEZ,None,1,CT01,2000-03-11 00:00:00,CONTADO,0.02,1
3,CT01,BELTRÁN E HIJOS,LAS FUENTES 78,MADRID,914456435,ANGEL MARTÍNEZ,None,74,CT01,2002-09-17 00:00:00,APLAZADO,0.08,0
4,CT01,BELTRÁN E HIJOS,LAS FUENTES 78,MADRID,914456435,ANGEL MARTÍNEZ,None,73,CT01,2001-08-02 00:00:00,CONTADO,0.07,0
5,CT01,BELTRÁN E HIJOS,LAS FUENTES 78,MADRID,914456435,ANGEL MARTÍNEZ,None,72,CT01,2002-08-18 00:00:00,CONTADO,0.05,1
6,CT01,BELTRÁN E HIJOS,LAS FUENTES 78,MADRID,914456435,ANGEL MARTÍNEZ,None,76,CT01,2002-10-19 00:00:00,CONTADO,0.04,1
7,CT01,BELTRÁN E HIJOS,LAS FUENTES 78,MADRID,914456435,ANGEL MARTÍNEZ,None,98,CT01,2001-12-27 00:00:00,CONTADO,0.08,1
8,CT01,BELTRÁN E HIJOS,LAS FUENTES 78,MADRID,914456435,ANGEL MARTÍNEZ,None,77,CT01,2000-10-28 00:00:00,CONTADO,0.05,0
9,CT04,EXPORTASA,VALLECAS 34,MADRID,913452378,ELVIRA GÓMEZ,None,11,CT04,2001-05-01 00:00:00,CONTADO,0.08,1
10,CT04,EXPORTASA,VALLECAS 34,MADRID,913452378,ELVIRA GÓMEZ,None,40,CT04,2002-07-12 00:00:00,CONTADO,0.12,0
11,CT04,EXPORTASA,VALLECAS 34,MADRID,913452378,ELVIRA GÓMEZ,None,85,CT04,2002-12-23 00:00:00,TARJETA,0.04,0
12,CT07,LA CASA DEL JUGUETE,AMÉRICA 45,MADRID,912649987,ELÍAS PÉREZ,None,22,CT07,2000-05-31 00:00:00,TARJETA,0.05,1
13,CT10,FERETERÍA EL CLAVO,PASEO DE ÁLAMOS 78,MADRID,914354866,MANUEL MENÉNDEZ,None,19,CT10,2002-05-22 00:00:00,CONTADO,0.07,1
14,CT14,DEPORTES GARCÍA,GUZMÁN EL BUENO 45,MADRID,913299475,ANA JIMÉNEZ,None,32,CT14,2001-06-20 00:00:00,APLAZADO,0.06,0
15,CT23,EL PALACIO DE LA MODA,ORTEGA Y GASSET 129,MADRID,927785235,LAURA CARRASCO,None,3,CT23,2000-03-18 00:00:00,APLAZADO,0.06,0
16,CT26,FERRETERÍA LA ESCOBA,ORENSE 7,MADRID,918459346,JOSÉ GARCÍA,None,35,CT26,2001-06-30 00:00:00,CONTADO,0.06,0
17,CT26,FERRETERÍA LA ESCOBA,ORENSE 7,MADRID,918459346,JOSÉ GARCÍA,None,34,CT26,2002-06-23 00:00:00,TARJETA,0.05,0
18,CT30,BAZAR EL ARGENTINO,ATOCHA 55,MADRID,912495973,ADRIÁN ÁLVAREZ,None,105,CT30,2001-01-01 00:00:00,APLAZADO,0.09,0
19,CT30,BAZAR EL ARGENTINO,ATOCHA 55,MADRID,912495973,ADRIÁN ÁLVAREZ,None,5005,CT30,2002-08-10 00:00:00,TARJETA,0.00,1
20,CT30,BAZAR EL ARGENTINO,ATOCHA 55,MADRID,912495973,ADRIÁN ÁLVAREZ,None,5050,CT30,2002-03-27 00:00:00,TARJETA,0.00,1
21,CT30,BAZAR EL ARGENTINO,ATOCHA 55,MADRID,912495973,ADRIÁN ÁLVAREZ,None,45,CT30,2002-07-22 00:00:00,TARJETA,0.07,0
22,CT30,BAZAR EL ARGENTINO,ATOCHA 55,MADRID,912495973,ADRIÁN ÁLVAREZ,None,31,CT30,2000-06-08 00:00:00,TARJETA,0.05,1
23,CT30,BAZAR EL ARGENTINO,ATOCHA 55,MADRID,912495973,ADRIÁN ÁLVAREZ,None,29,CT30,2001-04-02 00:00:00,TARJETA,0.06,0
24,CT34,BAZAR LA FARAONA,CASTILLA Y LEÓN 34,MADRID,915483627,ANGEL SANTAMARÍA,None,47,CT34,2000-07-31 00:00:00,APLAZADO,0.08,0
25,CT34,BAZAR LA FARAONA,CASTILLA Y LEÓN 34,MADRID,915483627,ANGEL SANTAMARÍA,None,79,CT34,2000-12-12 00:00:00,CONTADO,0.05,0
26,CT34,BAZAR LA FARAONA,CASTILLA Y LEÓN 34,MADRID,915483627,ANGEL SANTAMARÍA,None,44,CT34,2002-07-20 00:00:00,APLAZADO,0.04,0
27,CT34,BAZAR LA FARAONA,CASTILLA Y LEÓN 34,MADRID,915483627,ANGEL SANTAMARÍA,None,42,CT34,2002-07-15 00:00:00,APLAZADO,0.07,1
28,CT34,BAZAR LA FARAONA,CASTILLA Y LEÓN 34,MADRID,915483627,ANGEL SANTAMARÍA,None,27,CT34,2000-06-06 00:00:00,CONTADO,0.04,0

In [44]:
pd.read_sql("SELECT * FROM clientes_access AS c LEFT JOIN pedidos_access AS p ON c.`CÓDIGOCLIENTE`=p.`CÓDIGO CLIENTE` WHERE POBLACIÓN = 'MADRID' ORDER BY CÓDIGOCLIENTE",engine)

,CÓDIGOCLIENTE,EMPRESA,DIRECCIÓN,POBLACIÓN,TELÉFONO,RESPONSABLE,HISTORIAL,NÚMERO DE PEDIDO,CÓDIGO CLIENTE,FECHA DE PEDIDO,FORMA DE PAGO,DESCUENTO,ENVIADO
0,CT01,BELTRÁN E HIJOS,LAS FUENTES 78,MADRID,914456435,ANGEL MARTÍNEZ,None,1.0,CT01,2000-03-11 00:00:00,CONTADO,0.02,1.0
1,CT01,BELTRÁN E HIJOS,LAS FUENTES 78,MADRID,914456435,ANGEL MARTÍNEZ,None,98.0,CT01,2001-12-27 00:00:00,CONTADO,0.08,1.0
2,CT01,BELTRÁN E HIJOS,LAS FUENTES 78,MADRID,914456435,ANGEL MARTÍNEZ,None,8.0,CT01,2000-04-15 00:00:00,TARJETA,0.02,1.0
3,CT01,BELTRÁN E HIJOS,LAS FUENTES 78,MADRID,914456435,ANGEL MARTÍNEZ,None,72.0,CT01,2002-08-18 00:00:00,CONTADO,0.05,1.0
4,CT01,BELTRÁN E HIJOS,LAS FUENTES 78,MADRID,914456435,ANGEL MARTÍNEZ,None,73.0,CT01,2001-08-02 00:00:00,CONTADO,0.07,0.0
5,CT01,BELTRÁN E HIJOS,LAS FUENTES 78,MADRID,914456435,ANGEL MARTÍNEZ,None,74.0,CT01,2002-09-17 00:00:00,APLAZADO,0.08,0.0
6,CT01,BELTRÁN E HIJOS,LAS FUENTES 78,MADRID,914456435,ANGEL MARTÍNEZ,None,75.0,CT01,2002-09-30 00:00:00,TARJETA,0.12,0.0
7,CT01,BELTRÁN E HIJOS,LAS FUENTES 78,MADRID,914456435,ANGEL MARTÍNEZ,None,76.0,CT01,2002-10-19 00:00:00,CONTADO,0.04,1.0
8,CT01,BELTRÁN E HIJOS,LAS FUENTES 78,MADRID,914456435,ANGEL MARTÍNEZ,None,77.0,CT01,2000-10-28 00:00:00,CONTADO,0.05,0.0
9,CT04,EXPORTASA,VALLECAS 34,MADRID,913452378,ELVIRA GÓMEZ,None,85.0,CT04,2002-12-23 00:00:00,TARJETA,0.04,0.0
10,CT04,EXPORTASA,VALLECAS 34,MADRID,913452378,ELVIRA GÓMEZ,None,40.0,CT04,2002-07-12 00:00:00,CONTADO,0.12,0.0
11,CT04,EXPORTASA,VALLECAS 34,MADRID,913452378,ELVIRA GÓMEZ,None,11.0,CT04,2001-05-01 00:00:00,CONTADO,0.08,1.0
12,CT07,LA CASA DEL JUGUETE,AMÉRICA 45,MADRID,912649987,ELÍAS PÉREZ,None,22.0,CT07,2000-05-31 00:00:00,TARJETA,0.05,1.0
13,CT10,FERETERÍA EL CLAVO,PASEO DE ÁLAMOS 78,MADRID,914354866,MANUEL MENÉNDEZ,None,19.0,CT10,2002-05-22 00:00:00,CONTADO,0.07,1.0
14,CT14,DEPORTES GARCÍA,GUZMÁN EL BUENO 45,MADRID,913299475,ANA JIMÉNEZ,None,32.0,CT14,2001-06-20 00:00:00,APLAZADO,0.06,0.0
15,CT19,CONFECCIONES GALÁN,FUENCARRAL 78,MADRID,913859234,JUAN GARCÍA,None,NaN,NaN,NaN,NaN,NaN,NaN
16,CT23,EL PALACIO DE LA MODA,ORTEGA Y GASSET 129,MADRID,927785235,LAURA CARRASCO,None,3.0,CT23,2000-03-18 00:00:00,APLAZADO,0.06,0.0
17,CT26,FERRETERÍA LA ESCOBA,ORENSE 7,MADRID,918459346,JOSÉ GARCÍA,None,35.0,CT26,2001-06-30 00:00:00,CONTADO,0.06,0.0
18,CT26,FERRETERÍA LA ESCOBA,ORENSE 7,MADRID,918459346,JOSÉ GARCÍA,None,34.0,CT26,2002-06-23 00:00:00,TARJETA,0.05,0.0
19,CT30,BAZAR EL ARGENTINO,ATOCHA 55,MADRID,912495973,ADRIÁN ÁLVAREZ,None,5050.0,CT30,2002-03-27 00:00:00,TARJETA,0.00,1.0
20,CT30,BAZAR EL ARGENTINO,ATOCHA 55,MADRID,912495973,ADRIÁN ÁLVAREZ,None,5005.0,CT30,2002-08-10 00:00:00,TARJETA,0.00,1.0
21,CT30,BAZAR EL ARGENTINO,ATOCHA 55,MADRID,912495973,ADRIÁN ÁLVAREZ,None,105.0,CT30,2001-01-01 00:00:00,APLAZADO,0.09,0.0
22,CT30,BAZAR EL ARGENTINO,ATOCHA 55,MADRID,912495973,ADRIÁN ÁLVAREZ,None,45.0,CT30,2002-07-22 00:00:00,TARJETA,0.07,0.0
23,CT30,BAZAR EL ARGENTINO,ATOCHA 55,MADRID,912495973,ADRIÁN ÁLVAREZ,None,31.0,CT30,2000-06-08 00:00:00,TARJETA,0.05,1.0
24,CT30,BAZAR EL ARGENTINO,ATOCHA 55,MADRID,912495973,ADRIÁN ÁLVAREZ,None,29.0,CT30,2001-04-02 00:00:00,TARJETA,0.06,0.0
25,CT34,BAZAR LA FARAONA,CASTILLA Y LEÓN 34,MADRID,915483627,ANGEL SANTAMARÍA,None,79.0,CT34,2000-12-12 00:00:00,CONTADO,0.05,0.0
26,CT34,BAZAR LA FARAONA,CASTILLA Y LEÓN 34,MADRID,915483627,ANGEL SANTAMARÍA,None,47.0,CT34,2000-07-31 00:00:00,APLAZADO,0.08,0.0
27,CT34,BAZAR LA FARAONA,CASTILLA Y LEÓN 34,MADRID,915483627,ANGEL SANTAMARÍA,None,44.0,CT34,2002-07-20 00:00:00,APLAZADO,0.04,0.0
28,CT34,BAZAR LA FARAONA,CASTILLA Y LEÓN 34,MADRID,915483627,ANGEL SANTAMARÍA,None,42.0,CT34,2002-07-15 00:00:00,APLAZADO,0.07,1.0
29,CT34,BAZAR LA FARAONA,CASTILLA Y LEÓN 34,MADRID,915483627,ANGEL SANTAMARÍA,None,27.0,CT34,2000-06-06 00:00:00,CONTADO,0.04,0.0
30,CT36,JUGUETES EDUCATIVOS SANZ,ORENSE 89,MADRID,916872354,PEDRO IGLESIAS,None,NaN,NaN,NaN,NaN,NaN,NaN
31,CT39,FERRETERÍA LIMA,VALLECAS 45,MADRID,913532785,LUIS GARCÍA,None,NaN,NaN,NaN,NaN,NaN,NaN

In [45]:
pd.read_sql("SELECT * FROM pedidos",engine)

,NÚMERO DE PEDIDO,CÓDIGO CLIENTE,FECHA DE PEDIDO,FORMA DE PAGO,DESCUENTO,ENVIADO
0,1,CT01,11/03/2000,CONTADO,0.02,0
1,3,CT23,18/03/2000,APLAZADO,0.06,0
2,5,CT25,31/03/2000,CONTADO,0.09,0
3,7,CT12,12/04/2000,CONTADO,0.07,0
4,8,CT01,15/04/2000,TARJETA,0.02,0
5,9,CT21,21/04/2000,CONTADO,0.04,0
6,13,CT13,30/04/2000,APLAZADO,0.03,0
7,22,CT07,31/05/2000,TARJETA,0.05,0
8,25,CT18,02/06/2000,CONTADO,0.06,0
9,27,CT34,06/06/2000,CONTADO,0.04,0
10,31,CT30,08/06/2000,TARJETA,0.05,0
11,28,CT28,08/06/2000,APLAZADO,0.08,0
12,47,CT34,31/07/2000,APLAZADO,0.08,0
13,30,CT02,15/08/2000,CONTADO,0.06,0
14,63,CT28,10/09/2000,CONTADO,0.09,0
15,77,CT01,28/10/2000,CONTADO,0.05,0
16,79,CT34,12/12/2000,CONTADO,0.05,0
17,105,CT30,01/01/2001,APLAZADO,0.09,0
18,102,CT06,12/01/2001,CONTADO,0.07,0
19,103,CT02,24/01/2001,CONTADO,0.04,0
20,29,CT30,02/04/2001,TARJETA,0.06,0
21,11,CT04,01/05/2001,CONTADO,0.08,0
22,16,CT25,11/05/2001,CONTADO,0.12,0
23,12,CT06,19/05/2001,CONTADO,0.09,0
24,21,CT16,28/05/2001,CONTADO,0.03,0
25,26,CT09,04/06/2001,APLAZADO,0.07,0
26,32,CT14,20/06/2001,APLAZADO,0.06,0
27,35,CT26,30/06/2001,CONTADO,0.06,0
28,37,CT24,02/07/2001,TARJETA,0.03,0
29,39,CT20,08/07/2001,TARJETA,0.06,0
30,43,CT09,18/07/2001,CONTADO,0.07,0
31,73,CT01,02/08/2001,CONTADO,0.07,0
32,86,CT09,24/12/2001,APLAZADO,0.03,0
33,98,CT01,27/12/2001,CONTADO,0.08,0
34,5050,CT30,27/03/2002,TARJETA,0.00,0
35,19,CT10,22/05/2002,CONTADO,0.07,0
36,34,CT26,23/06/2002,TARJETA,0.05,0
37,40,CT04,12/07/2002,CONTADO,0.12,0
38,42,CT34,15/07/2002,APLAZADO,0.07,0
39,44,CT34,20/07/2002,APLAZADO,0.04,0
40,45,CT30,22/07/2002,TARJETA,0.07,0
41,46,CT31,25/07/2002,CONTADO,0.06,0
42,5005,CT30,10/08/2002,TARJETA,0.00,0
43,72,CT01,18/08/2002,CONTADO,0.05,0
44,48,CT18,30/08/2002,CONTADO,0.03,0
45,49,CT28,02/09/2002,CONTADO,0.03,0
46,50,CT09,05/09/2002,APLAZADO,0.08,0
47,51,CT09,05/09/2002,CONTADO,0.05,0
48,74,CT01,17/09/2002,APLAZADO,0.08,0
49,75,CT01,30/09/2002,TARJETA,0.12,0
50,76,CT01,19/10/2002,CONTADO,0.04,0
51,85,CT04,23/12/2002,TARJETA,0.04,0

In [46]:
pd.read_sql("SELECT * FROM clientes c LEFT JOIN pedidos AS p ON c.`CÓDIGOCLIENTE`=p.`CÓDIGO CLIENTE` WHERE POBLACIÓN = 'MADRID' AND p.`CÓDIGO CLIENTE` IS NULL ",engine)

,CÓDIGOCLIENTE,EMPRESA,DIRECCIÓN,POBLACIÓN,TELÉFONO,RESPONSABLE,HISTORIAL,NÚMERO DE PEDIDO,CÓDIGO CLIENTE,FECHA DE PEDIDO,FORMA DE PAGO,DESCUENTO,ENVIADO
0,CT19,CONFECCIONES GALÁN,FUENCARRAL 78,MADRID,913859234,JUAN GARCÍA,None,None,None,None,None,None,None
1,CT36,JUGUETES EDUCATIVOS SANZ,ORENSE 89,MADRID,916872354,PEDRO IGLESIAS,None,None,None,None,None,None,None
2,CT39,FERRETERÍA LIMA,VALLECAS 45,MADRID,913532785,LUIS GARCÍA,None,None,None,None,None,None,None

In [47]:
pd.read_sql("SELECT * FROM clientes",engine)

,CÓDIGOCLIENTE,EMPRESA,DIRECCIÓN,POBLACIÓN,TELÉFONO,RESPONSABLE,HISTORIAL
0,CT01,BELTRÁN E HIJOS,LAS FUENTES 78,MADRID,914456435,ANGEL MARTÍNEZ,None
1,CT02,LA MODERNA,LA PALOMA 123,OVIEDO,985323434,JUAN GARCÍA,None
2,CT03,EL ESPAÑOLITO,MOTORES 34,BARCELONA,934565343,ANA FERNÁNDEZ,None
3,CT04,EXPORTASA,VALLECAS 34,MADRID,913452378,ELVIRA GÓMEZ,None
4,CT06,CONFECCIONES AMPARO,LOS MOROS 23,GIJÓN,985754332,LUÍS ÁLVAREZ,None
5,CT07,LA CASA DEL JUGUETE,AMÉRICA 45,MADRID,912649987,ELÍAS PÉREZ,None
6,CT08,JUGUETERÍA SUÁREZ,PARIS 123,BARCELONA,933457866,JUAN GARCÍA,None
7,CT09,ALMACÉN POPULAR,LAS FUENTES 124,BILBAO,942347127,JOSÉ ÁLVAREZ,None
8,CT10,FERETERÍA EL CLAVO,PASEO DE ÁLAMOS 78,MADRID,914354866,MANUEL MENÉNDEZ,None
9,CT11,JUGUETES MARTÍNEZ,VIA LAYETANA 245,BARCELONA,936628554,FRANCISCO CUEVAS,None
10,CT12,FERNÁNDEZ SL,PASEO DEL MAR 45,SANTANDER,942049586,ELISA COLLADO,None
11,CT13,CONFECCIONES ARTÍMEZ,GENERAL PERÓN 45,A CORUÑA,981345239,ESTEBAN PASCUAL,None
12,CT14,DEPORTES GARCÍA,GUZMÁN EL BUENO 45,MADRID,913299475,ANA JIMÉNEZ,None
13,CT15,EXCLUSIVAS FERNÁNDEZ,LLOBREGAT 250,BARCELONA,939558365,LUISA FERNÁNDEZ,None
14,CT16,DEPORTES MORÁN,AUTONOMÍA 45,LUGO,982986944,JOSÉ MANZANO,None
15,CT17,BAZAR FRANCISCO,CARMEN 45,ZAMORA,980495288,CARLOS BELTRÁN,None
16,CT18,JUGUETES LA SONRISA,LA BAÑEZA 67,LEÓN,987945368,FAUSTINO PÉREZ,None
17,CT19,CONFECCIONES GALÁN,FUENCARRAL 78,MADRID,913859234,JUAN GARCÍA,None
18,CT20,LA CURTIDORA,OLIVARES 3,MÁLAGA,953756259,MARÍA GÓMEZ,None
19,CT21,LÍNEA JOVEN,SIERPES 78,SEVILLA,953452567,ASUNCIÓN SALADO,None
20,CT22,BAZAR EL BARAT,DIAGONAL 56,BARCELONA,936692866,ELISA DAPENA,None
21,CT23,EL PALACIO DE LA MODA,ORTEGA Y GASSET 129,MADRID,927785235,LAURA CARRASCO,None
22,CT24,SÁEZ Y CÍA,INFANTA MERCEDS 23,SEVILLA,954869234,MANUEL GUERRA,None
23,CT25,DEPORTES EL MADRILEÑO,CASTILLA 345,ZARAGOZA,976388934,CARLOS GONZÁLEZ,None
24,CT26,FERRETERÍA LA ESCOBA,ORENSE 7,MADRID,918459346,JOSÉ GARCÍA,None
25,CT27,JUGUETES EL BARATO,VÍA AUGUSTA 245,BARCELONA,933486984,ELVIRA IGLESIAS,None
26,CT28,CONFECCIONES HERMINIA,CORRIDA 345,GIJÓN,985597315,ABEL GONZÁLEZ,None
27,CT30,BAZAR EL ARGENTINO,ATOCHA 55,MADRID,912495973,ADRIÁN ÁLVAREZ,None
28,CT31,LA TIENDA ELEGANTE,EL COMENDADOR 67,ZARAGOZA,975694035,JOSÉ PASCUAL,None
29,CT32,DEPORTES NAUTICOS GARCÍA,JUAN FERNÁNDEZ 89,ÁVILA,920268648,JUAN CONRADO,None
30,CT33,CONFECCIONES RUIZ,LLOBREGAT 345,BARCELONA,934587615,CARLOS SANZ,None
31,CT34,BAZAR LA FARAONA,CASTILLA Y LEÓN 34,MADRID,915483627,ANGEL SANTAMARÍA,None
32,CT35,FERRETERÍA EL MARTILLO,CASTELLANOS 205,SALAMANCA,923548965,JOAQUÍN FERNANDEZ,None
33,CT36,JUGUETES EDUCATIVOS SANZ,ORENSE 89,MADRID,916872354,PEDRO IGLESIAS,None
34,CT37,ALMACENES FERNANDEZ,ANTÓN 67,TERUEL,978564025,MARIA ARDANZA,None
35,CT38,CONFECCIONES MÓNICA,MOTORES 67,BARCELONA,935681245,PEDRO SERRANO,None
36,CT39,FERRETERÍA LIMA,VALLECAS 45,MADRID,913532785,LUIS GARCÍA,None
37,CT40,DEPORTES EL BRASILEÑO,ABEL MARTÍNEZ 67,SALAMANCA,921548762,CARLOS GÓMEZ,None

### Subconsultas
Son consultas dentro de otras consultas
- Escalonada
- de lista
- correlacionada

In [ ]:
# Subconsulta escalonada
pd.read_sql("SELECT SECCIÓN, NOMBREARTÍCULO FROM productos WHERE PRECIO > (SELECT AVG(PRECIO) FROM productos)",engine)

      SECCIÓN    NOMBREARTÍCULO
0  CONFECCIÓN  ABRIGO CABALLERO

In [52]:
# Subconsulta de lista
pd.read_sql("(SELECT PRECIO FROM productos WHERE SECCIÓN = 'CERAMICA')",engine)

     PRECIO
0  168.4253
1   54.0911
2   43.2728
3   19.7468
4   29.0434
5  127.7704

In [54]:
pd.read_sql("SELECT * FROM productos WHERE PRECIO > ALL (SELECT PRECIO FROM productos WHERE SECCIÓN = 'CERAMICA')",engine)

,CÓDIGOARTÍCULO,SECCIÓN,NOMBREARTÍCULO,PRECIO,FECHA,IMPORTADO,PAÍSDEORIGEN,FOTO
0,AR02,CONFECCIÓN,TRAJE CABALLERO,284.5769,2002-03-11,0,ITALIA,None
1,AR09,CONFECCIÓN,PANTALÓN SEÑORA,174.2310,2000-01-10,0,MARRUECOS,None
2,AR10,JUGUETERÍA,CONSOLA VIDEO,442.5444,2002-09-24,0,USA,None
3,AR14,JUGUETERÍA,TREN ELÉCTRICO,1505.3766,2001-07-03,0,JAPÓN,None
4,AR23,CONFECCIÓN,CAZADORA PIEL,522.6930,2001-07-10,0,ITALIA,None
5,AR27,CONFECCIÓN,ABRIGO CABALLERO,500000.0000,2002-04-05,0,ITALIA,None
6,AR29,CONFECCIÓN,ABRIGO SRA,360.0736,2001-05-03,0,MARRUECOS,None
7,AR32,DEPORTES,CRONÓMETRO,439.1764,2002-01-03,0,USA,None
8,AR38,DEPORTES,CAÑA DE PESCA,270.0000,2000-02-14,0,USA,None

In [55]:
# Si cambiamos el ALL por el ANY entonces quiere decir que busca cualquier producto que tenga precio mayor a uno de los de la lista
pd.read_sql("SELECT * FROM productos WHERE PRECIO > ANY (SELECT PRECIO FROM productos WHERE SECCIÓN = 'CERAMICA')",engine)

,CÓDIGOARTÍCULO,SECCIÓN,NOMBREARTÍCULO,PRECIO,FECHA,IMPORTADO,PAÍSDEORIGEN,FOTO
0,AR02,CONFECCIÓN,TRAJE CABALLERO,284.5769,2002-03-11,0,ITALIA,None
1,AR03,JUGUETERÍA,COCHE TELEDIRIGIDO,159.4462,2002-05-26,0,MARRUECOS,None
2,AR04,DEPORTES,RAQUETA TENIS,93.4694,2000-03-20,0,USA,None
3,AR06,DEPORTES,MANCUERNAS,60.0000,2000-09-13,0,USA,None
4,AR07,CONFECCIÓN,SERRUCHO,30.2045,2001-03-23,0,FRANCIA,None
5,AR08,JUGUETERÍA,CORREPASILLOS,103.3356,2000-04-11,0,JAPÓN,None
6,AR09,CONFECCIÓN,PANTALÓN SEÑORA,174.2310,2000-01-10,0,MARRUECOS,None
7,AR10,JUGUETERÍA,CONSOLA VIDEO,442.5444,2002-09-24,0,USA,None
8,AR11,CERÁMICA,TUBOS,168.4253,2000-02-04,0,CHINA,None
9,AR12,FERRETERÍA,LLAVE INGLESA,24.3986,2001-05-23,0,USA,None
10,AR13,CONFECCIÓN,CAMISA CABALLERO,67.1306,2002-08-11,0,ESPAÑA,None
11,AR14,JUGUETERÍA,TREN ELÉCTRICO,1505.3766,2001-07-03,0,JAPÓN,None
12,AR15,CERÁMICA,PLATO DECORATIVO,54.0911,2000-06-07,0,CHINA,None
13,AR17,JUGUETERÍA,MUÑECA ANDADORA,105.0593,2001-01-04,0,ESPAÑA,None
14,AR18,DEPORTES,PISTOLA OLÍMPICA,46.7347,2001-02-02,0,SUECIA,None
15,AR19,CONFECCIÓN,BLUSA SRA.,101.0566,2000-03-18,0,CHINA,None
16,AR20,CERÁMICA,JUEGO DE TE,43.2728,2001-01-15,0,CHINA,None
17,AR23,CONFECCIÓN,CAZADORA PIEL,522.6930,2001-07-10,0,ITALIA,None
18,AR24,DEPORTES,BALÓN RUGBY,111.6440,2000-11-11,0,USA,None
19,AR25,DEPORTES,BALÓN BALONCESTO,75.2731,2001-06-25,0,JAPÓN,None
20,AR26,JUGUETERÍA,FUERTE DE SOLDADOS,143.7020,2000-11-25,0,JAPÓN,None
21,AR27,CONFECCIÓN,ABRIGO CABALLERO,500000.0000,2002-04-05,0,ITALIA,None
22,AR28,DEPORTES,BALÓN FÚTBOL,43.9147,2002-07-04,0,ESPAÑA,None
23,AR29,CONFECCIÓN,ABRIGO SRA,360.0736,2001-05-03,0,MARRUECOS,None
24,AR31,JUGUETERÍA,PISTOLA CON SONIDOS,57.2500,2001-04-15,0,ESPAÑA,None
25,AR32,DEPORTES,CRONÓMETRO,439.1764,2002-01-03,0,USA,None
26,AR33,CERÁMICA,MACETA,29.0434,2000-02-23,0,ESPAÑA,None
27,AR34,OFICINA,PIE DE LÁMPARA,39.7606,2001-05-27,0,TURQUÍA,None
28,AR35,FERRETERÍA,LIMA GRANDE,22.0692,2002-08-10,0,ESPAÑA,None
29,AR38,DEPORTES,CAÑA DE PESCA,270.0000,2000-02-14,0,USA,None
30,AR39,CERÁMICA,JARRA CHINA,127.7704,2002-09-02,0,CHINA,None
31,AR40,DEPORTES,BOTA ALPINISMO,144.0000,2002-05-05,0,ESPAÑA,None
32,AR41,DEPORTES,PALAS DE PING PONG,21.6000,2002-02-02,0,ESPAÑA,None

In [60]:
pd.read_sql("SELECT * FROM productos WHERE PRECIO > ALL (SELECT PRECIO FROM productos WHERE SECCIÓN = 'JUGUETERÍA')",engine)

,CÓDIGOARTÍCULO,SECCIÓN,NOMBREARTÍCULO,PRECIO,FECHA,IMPORTADO,PAÍSDEORIGEN,FOTO
0,AR27,CONFECCIÓN,ABRIGO CABALLERO,500000.0,2002-04-05,0,ITALIA,None

In [61]:
pd.read_sql("SELECT * FROM productos WHERE PRECIO > ANY (SELECT PRECIO FROM productos WHERE SECCIÓN = 'JUGUETERÍA')",engine)

,CÓDIGOARTÍCULO,SECCIÓN,NOMBREARTÍCULO,PRECIO,FECHA,IMPORTADO,PAÍSDEORIGEN,FOTO
0,AR02,CONFECCIÓN,TRAJE CABALLERO,284.5769,2002-03-11,0,ITALIA,None
1,AR03,JUGUETERÍA,COCHE TELEDIRIGIDO,159.4462,2002-05-26,0,MARRUECOS,None
2,AR04,DEPORTES,RAQUETA TENIS,93.4694,2000-03-20,0,USA,None
3,AR06,DEPORTES,MANCUERNAS,60.0000,2000-09-13,0,USA,None
4,AR08,JUGUETERÍA,CORREPASILLOS,103.3356,2000-04-11,0,JAPÓN,None
5,AR09,CONFECCIÓN,PANTALÓN SEÑORA,174.2310,2000-01-10,0,MARRUECOS,None
6,AR10,JUGUETERÍA,CONSOLA VIDEO,442.5444,2002-09-24,0,USA,None
7,AR11,CERÁMICA,TUBOS,168.4253,2000-02-04,0,CHINA,None
8,AR13,CONFECCIÓN,CAMISA CABALLERO,67.1306,2002-08-11,0,ESPAÑA,None
9,AR14,JUGUETERÍA,TREN ELÉCTRICO,1505.3766,2001-07-03,0,JAPÓN,None
10,AR17,JUGUETERÍA,MUÑECA ANDADORA,105.0593,2001-01-04,0,ESPAÑA,None
11,AR19,CONFECCIÓN,BLUSA SRA.,101.0566,2000-03-18,0,CHINA,None
12,AR23,CONFECCIÓN,CAZADORA PIEL,522.6930,2001-07-10,0,ITALIA,None
13,AR24,DEPORTES,BALÓN RUGBY,111.6440,2000-11-11,0,USA,None
14,AR25,DEPORTES,BALÓN BALONCESTO,75.2731,2001-06-25,0,JAPÓN,None
15,AR26,JUGUETERÍA,FUERTE DE SOLDADOS,143.7020,2000-11-25,0,JAPÓN,None
16,AR27,CONFECCIÓN,ABRIGO CABALLERO,500000.0000,2002-04-05,0,ITALIA,None
17,AR29,CONFECCIÓN,ABRIGO SRA,360.0736,2001-05-03,0,MARRUECOS,None
18,AR32,DEPORTES,CRONÓMETRO,439.1764,2002-01-03,0,USA,None
19,AR38,DEPORTES,CAÑA DE PESCA,270.0000,2000-02-14,0,USA,None
20,AR39,CERÁMICA,JARRA CHINA,127.7704,2002-09-02,0,CHINA,None
21,AR40,DEPORTES,BOTA ALPINISMO,144.0000,2002-05-05,0,ESPAÑA,None

In [73]:
pd.read_sql("SELECT NOMBREARTÍCULO,PRECIO FROM productos_access WHERE CÓDIGOARTÍCULO IN (SELECT `CÓDIGO ARTÍCULO` AS codigo FROM productos_pedidos_access WHERE UNIDADES > 20)",engine)

        NOMBREARTÍCULO    PRECIO
0        LLAVE INGLESA   24.3986
1             CENICERO   19.7468
2             MARTILLO   11.3952
3        CAZADORA PIEL  522.6930
4          BALÓN RUGBY  111.6440
5         BALÓN FÚTBOL   43.9147
6           ABRIGO SRA  360.0736
7  PISTOLA CON SONIDOS   57.2500
8          LIMA GRANDE   22.0692
9      JUEGO DE BROCAS   15.0950

### Consultas de accion
- Actualizacion
- Creacion
- Eliminacion 
- Datos anexados  

Comandos DML y DDL
- Create
- Update
- Delete
- Insert Into
- Select into

Las consultas de creacion de tabla no se realizan igual en todos los gestores de bases de datos

In [ ]:
pd.read_sql("")